<?php
/**
 * Locale
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Komoju
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * KOMOJU API
 *
 * Full featured access to the KOMOJU payments system.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.23.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Komoju\Model;
use \Komoju\ObjectSerializer;

/**
 * Locale Class Doc Comment
 *
 * @category Class
 * @description For supported payment methods, sets the language of the instruction page.
 * @package  Komoju
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class Locale
{
    /**
     * Possible values of this enum
     */
    public const JA = 'ja';

    public const EN = 'en';

    public const KO = 'ko';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::JA,
            self::EN,
            self::KO
        ];
    }
}


