<?php
/**
 * PaymentDetailsAll
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Komoju
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * KOMOJU API
 *
 * Full featured access to the KOMOJU payments system.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.23.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Komoju\Model;

use \ArrayAccess;
use \Komoju\ObjectSerializer;

/**
 * PaymentDetailsAll Class Doc Comment
 *
 * @category Class
 * @description Specify payment type and additional attributes required for each payment type.
 * @package  Komoju
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class PaymentDetailsAll implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = 'type';

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'PaymentDetailsAll';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'type' => 'string',
        'email' => 'string',
        'number' => 'string',
        'month' => 'int',
        'year' => 'int',
        'verification_value' => 'string',
        'name' => 'string',
        'given_name' => 'string',
        'family_name' => 'string',
        'expiry_days' => 'int',
        'intent' => '\Komoju\Model\Intent',
        'initiator' => 'string',
        'usage' => 'string',
        'scheme_reference' => 'string',
        'installments' => '\Komoju\Model\Installments',
        'shipping_address_name' => 'string',
        'shipping_address_line1' => 'string',
        'shipping_address_line2' => 'string',
        'shipping_address_city' => 'string',
        'shipping_address_state' => 'string',
        'shipping_address_zip' => 'string',
        'shipping_address_country' => 'string',
        'billing_address_name' => 'string',
        'billing_address_line1' => 'string',
        'billing_address_line2' => 'string',
        'billing_address_city' => 'string',
        'billing_address_state' => 'string',
        'billing_address_zip' => 'string',
        'billing_address_country' => 'string',
        'cpf_or_cnpj' => 'string',
        'customer_ip' => 'string',
        'corporate_card' => 'bool',
        'social_id' => '\Komoju\Model\PaymentDetailsCreditCardKoreaSocialId',
        'first_two_digits_of_pin' => 'string',
        'sequence_number' => 'string',
        'field55' => 'string',
        'pos_data_code' => 'string',
        'track2' => 'string',
        'flow_type' => 'string',
        'scanned_code' => 'string',
        'phone' => 'string',
        'given_name_kana' => 'string',
        'family_name_kana' => 'string',
        'prepaid_number' => 'string',
        'culture_id' => 'string',
        'culture_password' => 'string',
        'user_no' => 'string',
        'user_password' => 'string',
        'happy_money_id' => 'string',
        'happy_money_password' => 'string',
        'store' => 'string',
        'brand' => 'string',
        'customer_age' => 'int',
        'customer_last_order_amount' => 'int',
        'customer_last_order_at' => 'int',
        'customer_lifetime_value' => 'int',
        'customer_name' => 'string',
        'customer_order_count' => 'int',
        'external_customer_id' => 'string',
        'item_title' => 'string',
        'customer_name_kana' => 'string',
        'capture' => 'bool',
        'user_authorization_id' => 'string',
        'cpf' => 'string',
        'birthday' => 'string'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'type' => null,
        'email' => null,
        'number' => null,
        'month' => 'int32',
        'year' => 'int32',
        'verification_value' => null,
        'name' => null,
        'given_name' => null,
        'family_name' => null,
        'expiry_days' => 'int32',
        'intent' => null,
        'initiator' => null,
        'usage' => null,
        'scheme_reference' => null,
        'installments' => null,
        'shipping_address_name' => null,
        'shipping_address_line1' => null,
        'shipping_address_line2' => null,
        'shipping_address_city' => null,
        'shipping_address_state' => null,
        'shipping_address_zip' => null,
        'shipping_address_country' => null,
        'billing_address_name' => null,
        'billing_address_line1' => null,
        'billing_address_line2' => null,
        'billing_address_city' => null,
        'billing_address_state' => null,
        'billing_address_zip' => null,
        'billing_address_country' => null,
        'cpf_or_cnpj' => null,
        'customer_ip' => null,
        'corporate_card' => null,
        'social_id' => null,
        'first_two_digits_of_pin' => null,
        'sequence_number' => null,
        'field55' => null,
        'pos_data_code' => null,
        'track2' => null,
        'flow_type' => null,
        'scanned_code' => null,
        'phone' => null,
        'given_name_kana' => null,
        'family_name_kana' => null,
        'prepaid_number' => null,
        'culture_id' => null,
        'culture_password' => null,
        'user_no' => null,
        'user_password' => null,
        'happy_money_id' => null,
        'happy_money_password' => null,
        'store' => null,
        'brand' => null,
        'customer_age' => 'int32',
        'customer_last_order_amount' => 'int32',
        'customer_last_order_at' => 'int32',
        'customer_lifetime_value' => 'int32',
        'customer_name' => null,
        'customer_order_count' => 'int32',
        'external_customer_id' => null,
        'item_title' => null,
        'customer_name_kana' => null,
        'capture' => null,
        'user_authorization_id' => null,
        'cpf' => null,
        'birthday' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'type' => false,
        'email' => false,
        'number' => false,
        'month' => false,
        'year' => false,
        'verification_value' => false,
        'name' => false,
        'given_name' => false,
        'family_name' => false,
        'expiry_days' => false,
        'intent' => false,
        'initiator' => false,
        'usage' => false,
        'scheme_reference' => false,
        'installments' => false,
        'shipping_address_name' => false,
        'shipping_address_line1' => false,
        'shipping_address_line2' => false,
        'shipping_address_city' => false,
        'shipping_address_state' => false,
        'shipping_address_zip' => false,
        'shipping_address_country' => false,
        'billing_address_name' => false,
        'billing_address_line1' => false,
        'billing_address_line2' => false,
        'billing_address_city' => false,
        'billing_address_state' => false,
        'billing_address_zip' => false,
        'billing_address_country' => false,
        'cpf_or_cnpj' => false,
        'customer_ip' => false,
        'corporate_card' => false,
        'social_id' => false,
        'first_two_digits_of_pin' => false,
        'sequence_number' => false,
        'field55' => false,
        'pos_data_code' => false,
        'track2' => false,
        'flow_type' => false,
        'scanned_code' => false,
        'phone' => false,
        'given_name_kana' => false,
        'family_name_kana' => false,
        'prepaid_number' => false,
        'culture_id' => false,
        'culture_password' => false,
        'user_no' => false,
        'user_password' => false,
        'happy_money_id' => false,
        'happy_money_password' => false,
        'store' => false,
        'brand' => false,
        'customer_age' => false,
        'customer_last_order_amount' => false,
        'customer_last_order_at' => false,
        'customer_lifetime_value' => false,
        'customer_name' => false,
        'customer_order_count' => false,
        'external_customer_id' => false,
        'item_title' => false,
        'customer_name_kana' => false,
        'capture' => false,
        'user_authorization_id' => false,
        'cpf' => false,
        'birthday' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'type' => 'type',
        'email' => 'email',
        'number' => 'number',
        'month' => 'month',
        'year' => 'year',
        'verification_value' => 'verification_value',
        'name' => 'name',
        'given_name' => 'given_name',
        'family_name' => 'family_name',
        'expiry_days' => 'expiry_days',
        'intent' => 'intent',
        'initiator' => 'initiator',
        'usage' => 'usage',
        'scheme_reference' => 'scheme_reference',
        'installments' => 'installments',
        'shipping_address_name' => 'shipping_address_name',
        'shipping_address_line1' => 'shipping_address_line1',
        'shipping_address_line2' => 'shipping_address_line2',
        'shipping_address_city' => 'shipping_address_city',
        'shipping_address_state' => 'shipping_address_state',
        'shipping_address_zip' => 'shipping_address_zip',
        'shipping_address_country' => 'shipping_address_country',
        'billing_address_name' => 'billing_address_name',
        'billing_address_line1' => 'billing_address_line1',
        'billing_address_line2' => 'billing_address_line2',
        'billing_address_city' => 'billing_address_city',
        'billing_address_state' => 'billing_address_state',
        'billing_address_zip' => 'billing_address_zip',
        'billing_address_country' => 'billing_address_country',
        'cpf_or_cnpj' => 'cpf_or_cnpj',
        'customer_ip' => 'customer_ip',
        'corporate_card' => 'corporate_card',
        'social_id' => 'social_id',
        'first_two_digits_of_pin' => 'first_two_digits_of_pin',
        'sequence_number' => 'sequence_number',
        'field55' => 'field55',
        'pos_data_code' => 'posDataCode',
        'track2' => 'track2',
        'flow_type' => 'flowType',
        'scanned_code' => 'scanned_code',
        'phone' => 'phone',
        'given_name_kana' => 'given_name_kana',
        'family_name_kana' => 'family_name_kana',
        'prepaid_number' => 'prepaid_number',
        'culture_id' => 'culture_id',
        'culture_password' => 'culture_password',
        'user_no' => 'user_no',
        'user_password' => 'user_password',
        'happy_money_id' => 'happy_money_id',
        'happy_money_password' => 'happy_money_password',
        'store' => 'store',
        'brand' => 'brand',
        'customer_age' => 'customer_age',
        'customer_last_order_amount' => 'customer_last_order_amount',
        'customer_last_order_at' => 'customer_last_order_at',
        'customer_lifetime_value' => 'customer_lifetime_value',
        'customer_name' => 'customer_name',
        'customer_order_count' => 'customer_order_count',
        'external_customer_id' => 'external_customer_id',
        'item_title' => 'item_title',
        'customer_name_kana' => 'customer_name_kana',
        'capture' => 'capture',
        'user_authorization_id' => 'user_authorization_id',
        'cpf' => 'cpf',
        'birthday' => 'birthday'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'type' => 'setType',
        'email' => 'setEmail',
        'number' => 'setNumber',
        'month' => 'setMonth',
        'year' => 'setYear',
        'verification_value' => 'setVerificationValue',
        'name' => 'setName',
        'given_name' => 'setGivenName',
        'family_name' => 'setFamilyName',
        'expiry_days' => 'setExpiryDays',
        'intent' => 'setIntent',
        'initiator' => 'setInitiator',
        'usage' => 'setUsage',
        'scheme_reference' => 'setSchemeReference',
        'installments' => 'setInstallments',
        'shipping_address_name' => 'setShippingAddressName',
        'shipping_address_line1' => 'setShippingAddressLine1',
        'shipping_address_line2' => 'setShippingAddressLine2',
        'shipping_address_city' => 'setShippingAddressCity',
        'shipping_address_state' => 'setShippingAddressState',
        'shipping_address_zip' => 'setShippingAddressZip',
        'shipping_address_country' => 'setShippingAddressCountry',
        'billing_address_name' => 'setBillingAddressName',
        'billing_address_line1' => 'setBillingAddressLine1',
        'billing_address_line2' => 'setBillingAddressLine2',
        'billing_address_city' => 'setBillingAddressCity',
        'billing_address_state' => 'setBillingAddressState',
        'billing_address_zip' => 'setBillingAddressZip',
        'billing_address_country' => 'setBillingAddressCountry',
        'cpf_or_cnpj' => 'setCpfOrCnpj',
        'customer_ip' => 'setCustomerIp',
        'corporate_card' => 'setCorporateCard',
        'social_id' => 'setSocialId',
        'first_two_digits_of_pin' => 'setFirstTwoDigitsOfPin',
        'sequence_number' => 'setSequenceNumber',
        'field55' => 'setField55',
        'pos_data_code' => 'setPosDataCode',
        'track2' => 'setTrack2',
        'flow_type' => 'setFlowType',
        'scanned_code' => 'setScannedCode',
        'phone' => 'setPhone',
        'given_name_kana' => 'setGivenNameKana',
        'family_name_kana' => 'setFamilyNameKana',
        'prepaid_number' => 'setPrepaidNumber',
        'culture_id' => 'setCultureId',
        'culture_password' => 'setCulturePassword',
        'user_no' => 'setUserNo',
        'user_password' => 'setUserPassword',
        'happy_money_id' => 'setHappyMoneyId',
        'happy_money_password' => 'setHappyMoneyPassword',
        'store' => 'setStore',
        'brand' => 'setBrand',
        'customer_age' => 'setCustomerAge',
        'customer_last_order_amount' => 'setCustomerLastOrderAmount',
        'customer_last_order_at' => 'setCustomerLastOrderAt',
        'customer_lifetime_value' => 'setCustomerLifetimeValue',
        'customer_name' => 'setCustomerName',
        'customer_order_count' => 'setCustomerOrderCount',
        'external_customer_id' => 'setExternalCustomerId',
        'item_title' => 'setItemTitle',
        'customer_name_kana' => 'setCustomerNameKana',
        'capture' => 'setCapture',
        'user_authorization_id' => 'setUserAuthorizationId',
        'cpf' => 'setCpf',
        'birthday' => 'setBirthday'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'type' => 'getType',
        'email' => 'getEmail',
        'number' => 'getNumber',
        'month' => 'getMonth',
        'year' => 'getYear',
        'verification_value' => 'getVerificationValue',
        'name' => 'getName',
        'given_name' => 'getGivenName',
        'family_name' => 'getFamilyName',
        'expiry_days' => 'getExpiryDays',
        'intent' => 'getIntent',
        'initiator' => 'getInitiator',
        'usage' => 'getUsage',
        'scheme_reference' => 'getSchemeReference',
        'installments' => 'getInstallments',
        'shipping_address_name' => 'getShippingAddressName',
        'shipping_address_line1' => 'getShippingAddressLine1',
        'shipping_address_line2' => 'getShippingAddressLine2',
        'shipping_address_city' => 'getShippingAddressCity',
        'shipping_address_state' => 'getShippingAddressState',
        'shipping_address_zip' => 'getShippingAddressZip',
        'shipping_address_country' => 'getShippingAddressCountry',
        'billing_address_name' => 'getBillingAddressName',
        'billing_address_line1' => 'getBillingAddressLine1',
        'billing_address_line2' => 'getBillingAddressLine2',
        'billing_address_city' => 'getBillingAddressCity',
        'billing_address_state' => 'getBillingAddressState',
        'billing_address_zip' => 'getBillingAddressZip',
        'billing_address_country' => 'getBillingAddressCountry',
        'cpf_or_cnpj' => 'getCpfOrCnpj',
        'customer_ip' => 'getCustomerIp',
        'corporate_card' => 'getCorporateCard',
        'social_id' => 'getSocialId',
        'first_two_digits_of_pin' => 'getFirstTwoDigitsOfPin',
        'sequence_number' => 'getSequenceNumber',
        'field55' => 'getField55',
        'pos_data_code' => 'getPosDataCode',
        'track2' => 'getTrack2',
        'flow_type' => 'getFlowType',
        'scanned_code' => 'getScannedCode',
        'phone' => 'getPhone',
        'given_name_kana' => 'getGivenNameKana',
        'family_name_kana' => 'getFamilyNameKana',
        'prepaid_number' => 'getPrepaidNumber',
        'culture_id' => 'getCultureId',
        'culture_password' => 'getCulturePassword',
        'user_no' => 'getUserNo',
        'user_password' => 'getUserPassword',
        'happy_money_id' => 'getHappyMoneyId',
        'happy_money_password' => 'getHappyMoneyPassword',
        'store' => 'getStore',
        'brand' => 'getBrand',
        'customer_age' => 'getCustomerAge',
        'customer_last_order_amount' => 'getCustomerLastOrderAmount',
        'customer_last_order_at' => 'getCustomerLastOrderAt',
        'customer_lifetime_value' => 'getCustomerLifetimeValue',
        'customer_name' => 'getCustomerName',
        'customer_order_count' => 'getCustomerOrderCount',
        'external_customer_id' => 'getExternalCustomerId',
        'item_title' => 'getItemTitle',
        'customer_name_kana' => 'getCustomerNameKana',
        'capture' => 'getCapture',
        'user_authorization_id' => 'getUserAuthorizationId',
        'cpf' => 'getCpf',
        'birthday' => 'getBirthday'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const TYPE_CREDIT_CARD = 'credit_card';
    public const TYPE_CREDIT_CARD_BRAZIL = 'credit_card_brazil';
    public const TYPE_CREDIT_CARD_KOREA = 'credit_card_korea';
    public const TYPE_CREDIT_CARD_TERMINAL = 'credit_card_terminal';
    public const TYPE_ALIPAY = 'alipay';
    public const TYPE_ALIPAY_HK = 'alipay_hk';
    public const TYPE_AU = 'au';
    public const TYPE_AUPAY = 'aupay';
    public const TYPE_BANCONTACT = 'bancontact';
    public const TYPE_BANK_TRANSFER = 'bank_transfer';
    public const TYPE_BIT_CASH = 'bit_cash';
    public const TYPE_BLIK = 'blik';
    public const TYPE_CULTURE_VOUCHER = 'culture_voucher';
    public const TYPE_CVS = 'cvs';
    public const TYPE_DANA = 'dana';
    public const TYPE_DOCOMO = 'docomo';
    public const TYPE_DOKU_WALLET = 'doku_wallet';
    public const TYPE_DOSPARA = 'dospara';
    public const TYPE_DRAGONPAY = 'dragonpay';
    public const TYPE_ENETS = 'enets';
    public const TYPE_EPOSPAY = 'epospay';
    public const TYPE_EPS = 'eps';
    public const TYPE_FPX = 'fpx';
    public const TYPE_GCASH = 'gcash';
    public const TYPE_GIROPAY = 'giropay';
    public const TYPE_HAPPY_MONEY = 'happy_money';
    public const TYPE_IDEAL = 'ideal';
    public const TYPE_KAKAOPAY = 'kakaopay';
    public const TYPE_KONBINI = 'konbini';
    public const TYPE_MERPAY = 'merpay';
    public const TYPE_JAPAN_MOBILE = 'japan_mobile';
    public const TYPE_MOBILE = 'mobile';
    public const TYPE_MULTIBANCO = 'multibanco';
    public const TYPE_MYBANK = 'mybank';
    public const TYPE_NARVESEN = 'narvesen';
    public const TYPE_NAVERPAY = 'naverpay';
    public const TYPE_NET_CASH = 'net_cash';
    public const TYPE_OVO = 'ovo';
    public const TYPE_PAIDY = 'paidy';
    public const TYPE_PAYCO = 'payco';
    public const TYPE_PAY_EASY = 'pay_easy';
    public const TYPE_PAYPAY = 'paypay';
    public const TYPE_PAYPOST = 'paypost';
    public const TYPE_PAYSAFE_CARD = 'paysafe_card';
    public const TYPE_PAYSAFE_CASH = 'paysafe_cash';
    public const TYPE_PAYSERA = 'paysera';
    public const TYPE_PAYU = 'payu';
    public const TYPE_PERLAS = 'perlas';
    public const TYPE_PIX = 'pix';
    public const TYPE_POLI = 'poli';
    public const TYPE_PRZELEWY24 = 'przelewy24';
    public const TYPE_RAKUTENPAY = 'rakutenpay';
    public const TYPE_SEPA_TRANSFER = 'sepa_transfer';
    public const TYPE_SOFORTBANKING = 'sofortbanking';
    public const TYPE_SOFTBANK = 'softbank';
    public const TYPE_TOSS = 'toss';
    public const TYPE_TNG = 'tng';
    public const TYPE_TRUEMONEY = 'truemoney';
    public const TYPE_UNIONPAY = 'unionpay';
    public const TYPE_WEB_MONEY = 'web_money';
    public const TYPE_WECHATPAY = 'wechatpay';
    public const INITIATOR_MERCHANT = 'merchant';
    public const INITIATOR_CUSTOMER = 'customer';
    public const USAGE_FIRST = 'first';
    public const USAGE_USED = 'used';
    public const STORE_SEVEN_ELEVEN = 'seven-eleven';
    public const STORE_LAWSON = 'lawson';
    public const STORE_FAMILY_MART = 'family-mart';
    public const STORE_MINISTOP = 'ministop';
    public const STORE_DAILY_YAMAZAKI = 'daily-yamazaki';
    public const STORE_SEICOMART = 'seicomart';
    public const BRAND_AU = 'au';
    public const BRAND_DOCOMO = 'docomo';
    public const BRAND_SOFTBANK = 'softbank';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getTypeAllowableValues()
    {
        return [
            self::TYPE_CREDIT_CARD,
            self::TYPE_CREDIT_CARD_BRAZIL,
            self::TYPE_CREDIT_CARD_KOREA,
            self::TYPE_CREDIT_CARD_TERMINAL,
            self::TYPE_ALIPAY,
            self::TYPE_ALIPAY_HK,
            self::TYPE_AU,
            self::TYPE_AUPAY,
            self::TYPE_BANCONTACT,
            self::TYPE_BANK_TRANSFER,
            self::TYPE_BIT_CASH,
            self::TYPE_BLIK,
            self::TYPE_CULTURE_VOUCHER,
            self::TYPE_CVS,
            self::TYPE_DANA,
            self::TYPE_DOCOMO,
            self::TYPE_DOKU_WALLET,
            self::TYPE_DOSPARA,
            self::TYPE_DRAGONPAY,
            self::TYPE_ENETS,
            self::TYPE_EPOSPAY,
            self::TYPE_EPS,
            self::TYPE_FPX,
            self::TYPE_GCASH,
            self::TYPE_GIROPAY,
            self::TYPE_HAPPY_MONEY,
            self::TYPE_IDEAL,
            self::TYPE_KAKAOPAY,
            self::TYPE_KONBINI,
            self::TYPE_MERPAY,
            self::TYPE_JAPAN_MOBILE,
            self::TYPE_MOBILE,
            self::TYPE_MULTIBANCO,
            self::TYPE_MYBANK,
            self::TYPE_NARVESEN,
            self::TYPE_NAVERPAY,
            self::TYPE_NET_CASH,
            self::TYPE_OVO,
            self::TYPE_PAIDY,
            self::TYPE_PAYCO,
            self::TYPE_PAY_EASY,
            self::TYPE_PAYPAY,
            self::TYPE_PAYPOST,
            self::TYPE_PAYSAFE_CARD,
            self::TYPE_PAYSAFE_CASH,
            self::TYPE_PAYSERA,
            self::TYPE_PAYU,
            self::TYPE_PERLAS,
            self::TYPE_PIX,
            self::TYPE_POLI,
            self::TYPE_PRZELEWY24,
            self::TYPE_RAKUTENPAY,
            self::TYPE_SEPA_TRANSFER,
            self::TYPE_SOFORTBANKING,
            self::TYPE_SOFTBANK,
            self::TYPE_TOSS,
            self::TYPE_TNG,
            self::TYPE_TRUEMONEY,
            self::TYPE_UNIONPAY,
            self::TYPE_WEB_MONEY,
            self::TYPE_WECHATPAY,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getInitiatorAllowableValues()
    {
        return [
            self::INITIATOR_MERCHANT,
            self::INITIATOR_CUSTOMER,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getUsageAllowableValues()
    {
        return [
            self::USAGE_FIRST,
            self::USAGE_USED,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getStoreAllowableValues()
    {
        return [
            self::STORE_SEVEN_ELEVEN,
            self::STORE_LAWSON,
            self::STORE_FAMILY_MART,
            self::STORE_MINISTOP,
            self::STORE_DAILY_YAMAZAKI,
            self::STORE_SEICOMART,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getBrandAllowableValues()
    {
        return [
            self::BRAND_AU,
            self::BRAND_DOCOMO,
            self::BRAND_SOFTBANK,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('type', $data ?? [], null);
        $this->setIfExists('email', $data ?? [], null);
        $this->setIfExists('number', $data ?? [], null);
        $this->setIfExists('month', $data ?? [], null);
        $this->setIfExists('year', $data ?? [], null);
        $this->setIfExists('verification_value', $data ?? [], null);
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('given_name', $data ?? [], null);
        $this->setIfExists('family_name', $data ?? [], null);
        $this->setIfExists('expiry_days', $data ?? [], null);
        $this->setIfExists('intent', $data ?? [], null);
        $this->setIfExists('initiator', $data ?? [], null);
        $this->setIfExists('usage', $data ?? [], null);
        $this->setIfExists('scheme_reference', $data ?? [], null);
        $this->setIfExists('installments', $data ?? [], null);
        $this->setIfExists('shipping_address_name', $data ?? [], null);
        $this->setIfExists('shipping_address_line1', $data ?? [], null);
        $this->setIfExists('shipping_address_line2', $data ?? [], null);
        $this->setIfExists('shipping_address_city', $data ?? [], null);
        $this->setIfExists('shipping_address_state', $data ?? [], null);
        $this->setIfExists('shipping_address_zip', $data ?? [], null);
        $this->setIfExists('shipping_address_country', $data ?? [], null);
        $this->setIfExists('billing_address_name', $data ?? [], null);
        $this->setIfExists('billing_address_line1', $data ?? [], null);
        $this->setIfExists('billing_address_line2', $data ?? [], null);
        $this->setIfExists('billing_address_city', $data ?? [], null);
        $this->setIfExists('billing_address_state', $data ?? [], null);
        $this->setIfExists('billing_address_zip', $data ?? [], null);
        $this->setIfExists('billing_address_country', $data ?? [], null);
        $this->setIfExists('cpf_or_cnpj', $data ?? [], null);
        $this->setIfExists('customer_ip', $data ?? [], null);
        $this->setIfExists('corporate_card', $data ?? [], null);
        $this->setIfExists('social_id', $data ?? [], null);
        $this->setIfExists('first_two_digits_of_pin', $data ?? [], null);
        $this->setIfExists('sequence_number', $data ?? [], null);
        $this->setIfExists('field55', $data ?? [], null);
        $this->setIfExists('pos_data_code', $data ?? [], null);
        $this->setIfExists('track2', $data ?? [], null);
        $this->setIfExists('flow_type', $data ?? [], null);
        $this->setIfExists('scanned_code', $data ?? [], null);
        $this->setIfExists('phone', $data ?? [], null);
        $this->setIfExists('given_name_kana', $data ?? [], null);
        $this->setIfExists('family_name_kana', $data ?? [], null);
        $this->setIfExists('prepaid_number', $data ?? [], null);
        $this->setIfExists('culture_id', $data ?? [], null);
        $this->setIfExists('culture_password', $data ?? [], null);
        $this->setIfExists('user_no', $data ?? [], null);
        $this->setIfExists('user_password', $data ?? [], null);
        $this->setIfExists('happy_money_id', $data ?? [], null);
        $this->setIfExists('happy_money_password', $data ?? [], null);
        $this->setIfExists('store', $data ?? [], null);
        $this->setIfExists('brand', $data ?? [], null);
        $this->setIfExists('customer_age', $data ?? [], null);
        $this->setIfExists('customer_last_order_amount', $data ?? [], null);
        $this->setIfExists('customer_last_order_at', $data ?? [], null);
        $this->setIfExists('customer_lifetime_value', $data ?? [], null);
        $this->setIfExists('customer_name', $data ?? [], null);
        $this->setIfExists('customer_order_count', $data ?? [], null);
        $this->setIfExists('external_customer_id', $data ?? [], null);
        $this->setIfExists('item_title', $data ?? [], null);
        $this->setIfExists('customer_name_kana', $data ?? [], null);
        $this->setIfExists('capture', $data ?? [], null);
        $this->setIfExists('user_authorization_id', $data ?? [], null);
        $this->setIfExists('cpf', $data ?? [], null);
        $this->setIfExists('birthday', $data ?? [], null);

        // Initialize discriminator property with the model name.
        $this->container['type'] = static::$openAPIModelName;
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['type'] === null) {
            $invalidProperties[] = "'type' can't be null";
        }
        if ($this->container['email'] === null) {
            $invalidProperties[] = "'email' can't be null";
        }
        if ($this->container['number'] === null) {
            $invalidProperties[] = "'number' can't be null";
        }
        if ((mb_strlen($this->container['number']) > 19)) {
            $invalidProperties[] = "invalid value for 'number', the character length must be smaller than or equal to 19.";
        }

        if ((mb_strlen($this->container['number']) < 8)) {
            $invalidProperties[] = "invalid value for 'number', the character length must be bigger than or equal to 8.";
        }

        if ($this->container['month'] === null) {
            $invalidProperties[] = "'month' can't be null";
        }
        if (($this->container['month'] > 12)) {
            $invalidProperties[] = "invalid value for 'month', must be smaller than or equal to 12.";
        }

        if (($this->container['month'] < 1)) {
            $invalidProperties[] = "invalid value for 'month', must be bigger than or equal to 1.";
        }

        if ($this->container['year'] === null) {
            $invalidProperties[] = "'year' can't be null";
        }
        if (($this->container['year'] > 2100)) {
            $invalidProperties[] = "invalid value for 'year', must be smaller than or equal to 2100.";
        }

        if (($this->container['year'] < 0)) {
            $invalidProperties[] = "invalid value for 'year', must be bigger than or equal to 0.";
        }

        if ($this->container['verification_value'] === null) {
            $invalidProperties[] = "'verification_value' can't be null";
        }
        if ($this->container['name'] === null) {
            $invalidProperties[] = "'name' can't be null";
        }
        if ((mb_strlen($this->container['name']) > 255)) {
            $invalidProperties[] = "invalid value for 'name', the character length must be smaller than or equal to 255.";
        }

        if ($this->container['given_name'] === null) {
            $invalidProperties[] = "'given_name' can't be null";
        }
        if ((mb_strlen($this->container['given_name']) > 255)) {
            $invalidProperties[] = "invalid value for 'given_name', the character length must be smaller than or equal to 255.";
        }

        if ($this->container['family_name'] === null) {
            $invalidProperties[] = "'family_name' can't be null";
        }
        if ((mb_strlen($this->container['family_name']) > 255)) {
            $invalidProperties[] = "invalid value for 'family_name', the character length must be smaller than or equal to 255.";
        }

        if ($this->container['cpf_or_cnpj'] === null) {
            $invalidProperties[] = "'cpf_or_cnpj' can't be null";
        }
        if ($this->container['customer_ip'] === null) {
            $invalidProperties[] = "'customer_ip' can't be null";
        }
        if ($this->container['first_two_digits_of_pin'] === null) {
            $invalidProperties[] = "'first_two_digits_of_pin' can't be null";
        }
        if ((mb_strlen($this->container['first_two_digits_of_pin']) > 2)) {
            $invalidProperties[] = "invalid value for 'first_two_digits_of_pin', the character length must be smaller than or equal to 2.";
        }

        if ((mb_strlen($this->container['first_two_digits_of_pin']) < 2)) {
            $invalidProperties[] = "invalid value for 'first_two_digits_of_pin', the character length must be bigger than or equal to 2.";
        }

        if ($this->container['phone'] === null) {
            $invalidProperties[] = "'phone' can't be null";
        }
        if (!preg_match("/\\A([() \\-_+]*[0-9]){10}[() \\-_+0-9]*\\Z/", $this->container['phone'])) {
            $invalidProperties[] = "invalid value for 'phone', must be conform to the pattern /\\A([() \\-_+]*[0-9]){10}[() \\-_+0-9]*\\Z/.";
        }

        if ($this->container['given_name_kana'] === null) {
            $invalidProperties[] = "'given_name_kana' can't be null";
        }
        if ((mb_strlen($this->container['given_name_kana']) > 255)) {
            $invalidProperties[] = "invalid value for 'given_name_kana', the character length must be smaller than or equal to 255.";
        }

        if ($this->container['family_name_kana'] === null) {
            $invalidProperties[] = "'family_name_kana' can't be null";
        }
        if ((mb_strlen($this->container['family_name_kana']) > 255)) {
            $invalidProperties[] = "invalid value for 'family_name_kana', the character length must be smaller than or equal to 255.";
        }

        if ($this->container['prepaid_number'] === null) {
            $invalidProperties[] = "'prepaid_number' can't be null";
        }
        if ((mb_strlen($this->container['prepaid_number']) > 16)) {
            $invalidProperties[] = "invalid value for 'prepaid_number', the character length must be smaller than or equal to 16.";
        }

        if ((mb_strlen($this->container['prepaid_number']) < 16)) {
            $invalidProperties[] = "invalid value for 'prepaid_number', the character length must be bigger than or equal to 16.";
        }

        if ($this->container['culture_id'] === null) {
            $invalidProperties[] = "'culture_id' can't be null";
        }
        if ((mb_strlen($this->container['culture_id']) > 12)) {
            $invalidProperties[] = "invalid value for 'culture_id', the character length must be smaller than or equal to 12.";
        }

        if ((mb_strlen($this->container['culture_id']) < 1)) {
            $invalidProperties[] = "invalid value for 'culture_id', the character length must be bigger than or equal to 1.";
        }

        if ($this->container['culture_password'] === null) {
            $invalidProperties[] = "'culture_password' can't be null";
        }
        if ((mb_strlen($this->container['culture_password']) > 20)) {
            $invalidProperties[] = "invalid value for 'culture_password', the character length must be smaller than or equal to 20.";
        }

        if ((mb_strlen($this->container['culture_password']) < 1)) {
            $invalidProperties[] = "invalid value for 'culture_password', the character length must be bigger than or equal to 1.";
        }

        if ($this->container['user_no'] === null) {
            $invalidProperties[] = "'user_no' can't be null";
        }
        if ((mb_strlen($this->container['user_no']) > 20)) {
            $invalidProperties[] = "invalid value for 'user_no', the character length must be smaller than or equal to 20.";
        }

        if ($this->container['user_password'] === null) {
            $invalidProperties[] = "'user_password' can't be null";
        }
        if ((mb_strlen($this->container['user_password']) > 20)) {
            $invalidProperties[] = "invalid value for 'user_password', the character length must be smaller than or equal to 20.";
        }

        if ($this->container['happy_money_id'] === null) {
            $invalidProperties[] = "'happy_money_id' can't be null";
        }
        if ((mb_strlen($this->container['happy_money_id']) > 20)) {
            $invalidProperties[] = "invalid value for 'happy_money_id', the character length must be smaller than or equal to 20.";
        }

        if ((mb_strlen($this->container['happy_money_id']) < 1)) {
            $invalidProperties[] = "invalid value for 'happy_money_id', the character length must be bigger than or equal to 1.";
        }

        if ($this->container['happy_money_password'] === null) {
            $invalidProperties[] = "'happy_money_password' can't be null";
        }
        if ((mb_strlen($this->container['happy_money_password']) > 50)) {
            $invalidProperties[] = "invalid value for 'happy_money_password', the character length must be smaller than or equal to 50.";
        }

        if ((mb_strlen($this->container['happy_money_password']) < 1)) {
            $invalidProperties[] = "invalid value for 'happy_money_password', the character length must be bigger than or equal to 1.";
        }

        if ($this->container['store'] === null) {
            $invalidProperties[] = "'store' can't be null";
        }
        if ($this->container['brand'] === null) {
            $invalidProperties[] = "'brand' can't be null";
        }
        if ($this->container['customer_name'] === null) {
            $invalidProperties[] = "'customer_name' can't be null";
        }
        if ($this->container['cpf'] === null) {
            $invalidProperties[] = "'cpf' can't be null";
        }
        if (!preg_match("/([0-9]{3}[.]?[0-9]{3}[.]?[0-9]{3}[-]?[0-9]{2})/", $this->container['cpf'])) {
            $invalidProperties[] = "invalid value for 'cpf', must be conform to the pattern /([0-9]{3}[.]?[0-9]{3}[.]?[0-9]{3}[-]?[0-9]{2})/.";
        }

        if ($this->container['birthday'] === null) {
            $invalidProperties[] = "'birthday' can't be null";
        }
        if ((mb_strlen($this->container['birthday']) > 6)) {
            $invalidProperties[] = "invalid value for 'birthday', the character length must be smaller than or equal to 6.";
        }

        if ((mb_strlen($this->container['birthday']) < 6)) {
            $invalidProperties[] = "invalid value for 'birthday', the character length must be bigger than or equal to 6.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets type
     *
     * @return string
     */
    public function getType()
    {
        return $this->container['type'];
    }

    /**
     * Sets type
     *
     * @param string $type Payment method type.
     *
     * @return self
     */
    public function setType($type)
    {
        if (is_null($type)) {
            throw new \InvalidArgumentException('non-nullable type cannot be null');
        }
        $this->container['type'] = $type;

        return $this;
    }

    /**
     * Gets email
     *
     * @return string
     */
    public function getEmail()
    {
        return $this->container['email'];
    }

    /**
     * Sets email
     *
     * @param string $email Customer's email address. Will be used for fraud prevention and payment receipt.
     *
     * @return self
     */
    public function setEmail($email)
    {
        if (is_null($email)) {
            throw new \InvalidArgumentException('non-nullable email cannot be null');
        }
        $this->container['email'] = $email;

        return $this;
    }

    /**
     * Gets number
     *
     * @return string
     */
    public function getNumber()
    {
        return $this->container['number'];
    }

    /**
     * Sets number
     *
     * @param string $number Credit card number.
     *
     * @return self
     */
    public function setNumber($number)
    {
        if (is_null($number)) {
            throw new \InvalidArgumentException('non-nullable number cannot be null');
        }
        if ((mb_strlen($number) > 19)) {
            throw new \InvalidArgumentException('invalid length for $number when calling PaymentDetailsAll., must be smaller than or equal to 19.');
        }
        if ((mb_strlen($number) < 8)) {
            throw new \InvalidArgumentException('invalid length for $number when calling PaymentDetailsAll., must be bigger than or equal to 8.');
        }

        $this->container['number'] = $number;

        return $this;
    }

    /**
     * Gets month
     *
     * @return int
     */
    public function getMonth()
    {
        return $this->container['month'];
    }

    /**
     * Sets month
     *
     * @param int $month Credit card expiration month.
     *
     * @return self
     */
    public function setMonth($month)
    {
        if (is_null($month)) {
            throw new \InvalidArgumentException('non-nullable month cannot be null');
        }

        if (($month > 12)) {
            throw new \InvalidArgumentException('invalid value for $month when calling PaymentDetailsAll., must be smaller than or equal to 12.');
        }
        if (($month < 1)) {
            throw new \InvalidArgumentException('invalid value for $month when calling PaymentDetailsAll., must be bigger than or equal to 1.');
        }

        $this->container['month'] = $month;

        return $this;
    }

    /**
     * Gets year
     *
     * @return int
     */
    public function getYear()
    {
        return $this->container['year'];
    }

    /**
     * Sets year
     *
     * @param int $year Credit card expiration year.  If this value is less than 100, it will be treated as two digits year in the current century. E.g. If current year is `2024`, `99` means `2099`.
     *
     * @return self
     */
    public function setYear($year)
    {
        if (is_null($year)) {
            throw new \InvalidArgumentException('non-nullable year cannot be null');
        }

        if (($year > 2100)) {
            throw new \InvalidArgumentException('invalid value for $year when calling PaymentDetailsAll., must be smaller than or equal to 2100.');
        }
        if (($year < 0)) {
            throw new \InvalidArgumentException('invalid value for $year when calling PaymentDetailsAll., must be bigger than or equal to 0.');
        }

        $this->container['year'] = $year;

        return $this;
    }

    /**
     * Gets verification_value
     *
     * @return string
     */
    public function getVerificationValue()
    {
        return $this->container['verification_value'];
    }

    /**
     * Sets verification_value
     *
     * @param string $verification_value Credit card verification value (Also known as CVV2 or CVC2).
     *
     * @return self
     */
    public function setVerificationValue($verification_value)
    {
        if (is_null($verification_value)) {
            throw new \InvalidArgumentException('non-nullable verification_value cannot be null');
        }
        $this->container['verification_value'] = $verification_value;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string $name Full name of the customer.  This attribute takes precedence over `given_name` and `family_name`.
     *
     * @return self
     */
    public function setName($name)
    {
        if (is_null($name)) {
            throw new \InvalidArgumentException('non-nullable name cannot be null');
        }
        if ((mb_strlen($name) > 255)) {
            throw new \InvalidArgumentException('invalid length for $name when calling PaymentDetailsAll., must be smaller than or equal to 255.');
        }

        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets given_name
     *
     * @return string
     */
    public function getGivenName()
    {
        return $this->container['given_name'];
    }

    /**
     * Sets given_name
     *
     * @param string $given_name Given name of the customer.
     *
     * @return self
     */
    public function setGivenName($given_name)
    {
        if (is_null($given_name)) {
            throw new \InvalidArgumentException('non-nullable given_name cannot be null');
        }
        if ((mb_strlen($given_name) > 255)) {
            throw new \InvalidArgumentException('invalid length for $given_name when calling PaymentDetailsAll., must be smaller than or equal to 255.');
        }

        $this->container['given_name'] = $given_name;

        return $this;
    }

    /**
     * Gets family_name
     *
     * @return string
     */
    public function getFamilyName()
    {
        return $this->container['family_name'];
    }

    /**
     * Sets family_name
     *
     * @param string $family_name Family name of the customer.
     *
     * @return self
     */
    public function setFamilyName($family_name)
    {
        if (is_null($family_name)) {
            throw new \InvalidArgumentException('non-nullable family_name cannot be null');
        }
        if ((mb_strlen($family_name) > 255)) {
            throw new \InvalidArgumentException('invalid length for $family_name when calling PaymentDetailsAll., must be smaller than or equal to 255.');
        }

        $this->container['family_name'] = $family_name;

        return $this;
    }

    /**
     * Gets expiry_days
     *
     * @return int|null
     */
    public function getExpiryDays()
    {
        return $this->container['expiry_days'];
    }

    /**
     * Sets expiry_days
     *
     * @param int|null $expiry_days Specify how many days before the payment expires.  If this value is omitted, the default expiry day shown in the merchant dashboard will be used.
     *
     * @return self
     */
    public function setExpiryDays($expiry_days)
    {
        if (is_null($expiry_days)) {
            throw new \InvalidArgumentException('non-nullable expiry_days cannot be null');
        }
        $this->container['expiry_days'] = $expiry_days;

        return $this;
    }

    /**
     * Gets intent
     *
     * @return \Komoju\Model\Intent|null
     */
    public function getIntent()
    {
        return $this->container['intent'];
    }

    /**
     * Sets intent
     *
     * @param \Komoju\Model\Intent|null $intent intent
     *
     * @return self
     */
    public function setIntent($intent)
    {
        if (is_null($intent)) {
            throw new \InvalidArgumentException('non-nullable intent cannot be null');
        }
        $this->container['intent'] = $intent;

        return $this;
    }

    /**
     * Gets initiator
     *
     * @return string|null
     */
    public function getInitiator()
    {
        return $this->container['initiator'];
    }

    /**
     * Sets initiator
     *
     * @param string|null $initiator Specify the initiator of this payment.  Specifying this attribute can increase authorization credit card payments authorization rates, especially when using a stored card.  You can set this value to `customer` when the payment is being made for one-time goods or service purchase, or `merchant` for recurring subscription or installment payments.
     *
     * @return self
     */
    public function setInitiator($initiator)
    {
        if (is_null($initiator)) {
            throw new \InvalidArgumentException('non-nullable initiator cannot be null');
        }
        $this->container['initiator'] = $initiator;

        return $this;
    }

    /**
     * Gets usage
     *
     * @return string|null
     */
    public function getUsage()
    {
        return $this->container['usage'];
    }

    /**
     * Sets usage
     *
     * @param string|null $usage Specify whether this payment is the first (`first`) or a subsequent payment in a series (`used`).  Specifying this attribute can increase authorization credit card payments authorization rates, especially when using a stored card.
     *
     * @return self
     */
    public function setUsage($usage)
    {
        if (is_null($usage)) {
            throw new \InvalidArgumentException('non-nullable usage cannot be null');
        }
        $this->container['usage'] = $usage;

        return $this;
    }

    /**
     * Gets scheme_reference
     *
     * @return string|null
     */
    public function getSchemeReference()
    {
        return $this->container['scheme_reference'];
    }

    /**
     * Sets scheme_reference
     *
     * @param string|null $scheme_reference Specify a scheme reference value, which is used to track the chain of multiple related payments.  This value can be subscription number for a recurring subscription payments, or installment agreement number for installment payments.  Specifying this attribute can increase authorization credit card payments authorization rates, especially when using a stored card.
     *
     * @return self
     */
    public function setSchemeReference($scheme_reference)
    {
        if (is_null($scheme_reference)) {
            throw new \InvalidArgumentException('non-nullable scheme_reference cannot be null');
        }
        $this->container['scheme_reference'] = $scheme_reference;

        return $this;
    }

    /**
     * Gets installments
     *
     * @return \Komoju\Model\Installments|null
     */
    public function getInstallments()
    {
        return $this->container['installments'];
    }

    /**
     * Sets installments
     *
     * @param \Komoju\Model\Installments|null $installments installments
     *
     * @return self
     */
    public function setInstallments($installments)
    {
        if (is_null($installments)) {
            throw new \InvalidArgumentException('non-nullable installments cannot be null');
        }
        $this->container['installments'] = $installments;

        return $this;
    }

    /**
     * Gets shipping_address_name
     *
     * @return string|null
     */
    public function getShippingAddressName()
    {
        return $this->container['shipping_address_name'];
    }

    /**
     * Sets shipping_address_name
     *
     * @param string|null $shipping_address_name Shipping address name. This is the recipient's name.
     *
     * @return self
     */
    public function setShippingAddressName($shipping_address_name)
    {
        if (is_null($shipping_address_name)) {
            throw new \InvalidArgumentException('non-nullable shipping_address_name cannot be null');
        }
        $this->container['shipping_address_name'] = $shipping_address_name;

        return $this;
    }

    /**
     * Gets shipping_address_line1
     *
     * @return string|null
     */
    public function getShippingAddressLine1()
    {
        return $this->container['shipping_address_line1'];
    }

    /**
     * Sets shipping_address_line1
     *
     * @param string|null $shipping_address_line1 Shipping address line 1.
     *
     * @return self
     */
    public function setShippingAddressLine1($shipping_address_line1)
    {
        if (is_null($shipping_address_line1)) {
            throw new \InvalidArgumentException('non-nullable shipping_address_line1 cannot be null');
        }
        $this->container['shipping_address_line1'] = $shipping_address_line1;

        return $this;
    }

    /**
     * Gets shipping_address_line2
     *
     * @return string|null
     */
    public function getShippingAddressLine2()
    {
        return $this->container['shipping_address_line2'];
    }

    /**
     * Sets shipping_address_line2
     *
     * @param string|null $shipping_address_line2 Shipping address line 2.
     *
     * @return self
     */
    public function setShippingAddressLine2($shipping_address_line2)
    {
        if (is_null($shipping_address_line2)) {
            throw new \InvalidArgumentException('non-nullable shipping_address_line2 cannot be null');
        }
        $this->container['shipping_address_line2'] = $shipping_address_line2;

        return $this;
    }

    /**
     * Gets shipping_address_city
     *
     * @return string|null
     */
    public function getShippingAddressCity()
    {
        return $this->container['shipping_address_city'];
    }

    /**
     * Sets shipping_address_city
     *
     * @param string|null $shipping_address_city Shipping address city.
     *
     * @return self
     */
    public function setShippingAddressCity($shipping_address_city)
    {
        if (is_null($shipping_address_city)) {
            throw new \InvalidArgumentException('non-nullable shipping_address_city cannot be null');
        }
        $this->container['shipping_address_city'] = $shipping_address_city;

        return $this;
    }

    /**
     * Gets shipping_address_state
     *
     * @return string|null
     */
    public function getShippingAddressState()
    {
        return $this->container['shipping_address_state'];
    }

    /**
     * Sets shipping_address_state
     *
     * @param string|null $shipping_address_state Shipping address state.
     *
     * @return self
     */
    public function setShippingAddressState($shipping_address_state)
    {
        if (is_null($shipping_address_state)) {
            throw new \InvalidArgumentException('non-nullable shipping_address_state cannot be null');
        }
        $this->container['shipping_address_state'] = $shipping_address_state;

        return $this;
    }

    /**
     * Gets shipping_address_zip
     *
     * @return string|null
     */
    public function getShippingAddressZip()
    {
        return $this->container['shipping_address_zip'];
    }

    /**
     * Sets shipping_address_zip
     *
     * @param string|null $shipping_address_zip Shipping address ZIP code.
     *
     * @return self
     */
    public function setShippingAddressZip($shipping_address_zip)
    {
        if (is_null($shipping_address_zip)) {
            throw new \InvalidArgumentException('non-nullable shipping_address_zip cannot be null');
        }
        $this->container['shipping_address_zip'] = $shipping_address_zip;

        return $this;
    }

    /**
     * Gets shipping_address_country
     *
     * @return string|null
     */
    public function getShippingAddressCountry()
    {
        return $this->container['shipping_address_country'];
    }

    /**
     * Sets shipping_address_country
     *
     * @param string|null $shipping_address_country Shipping address country.
     *
     * @return self
     */
    public function setShippingAddressCountry($shipping_address_country)
    {
        if (is_null($shipping_address_country)) {
            throw new \InvalidArgumentException('non-nullable shipping_address_country cannot be null');
        }
        $this->container['shipping_address_country'] = $shipping_address_country;

        return $this;
    }

    /**
     * Gets billing_address_name
     *
     * @return string|null
     */
    public function getBillingAddressName()
    {
        return $this->container['billing_address_name'];
    }

    /**
     * Sets billing_address_name
     *
     * @param string|null $billing_address_name Billing address name. This is the paying customer's name.
     *
     * @return self
     */
    public function setBillingAddressName($billing_address_name)
    {
        if (is_null($billing_address_name)) {
            throw new \InvalidArgumentException('non-nullable billing_address_name cannot be null');
        }
        $this->container['billing_address_name'] = $billing_address_name;

        return $this;
    }

    /**
     * Gets billing_address_line1
     *
     * @return string|null
     */
    public function getBillingAddressLine1()
    {
        return $this->container['billing_address_line1'];
    }

    /**
     * Sets billing_address_line1
     *
     * @param string|null $billing_address_line1 Billing address line 1.
     *
     * @return self
     */
    public function setBillingAddressLine1($billing_address_line1)
    {
        if (is_null($billing_address_line1)) {
            throw new \InvalidArgumentException('non-nullable billing_address_line1 cannot be null');
        }
        $this->container['billing_address_line1'] = $billing_address_line1;

        return $this;
    }

    /**
     * Gets billing_address_line2
     *
     * @return string|null
     */
    public function getBillingAddressLine2()
    {
        return $this->container['billing_address_line2'];
    }

    /**
     * Sets billing_address_line2
     *
     * @param string|null $billing_address_line2 Billing address line 2.
     *
     * @return self
     */
    public function setBillingAddressLine2($billing_address_line2)
    {
        if (is_null($billing_address_line2)) {
            throw new \InvalidArgumentException('non-nullable billing_address_line2 cannot be null');
        }
        $this->container['billing_address_line2'] = $billing_address_line2;

        return $this;
    }

    /**
     * Gets billing_address_city
     *
     * @return string|null
     */
    public function getBillingAddressCity()
    {
        return $this->container['billing_address_city'];
    }

    /**
     * Sets billing_address_city
     *
     * @param string|null $billing_address_city Billing address city.
     *
     * @return self
     */
    public function setBillingAddressCity($billing_address_city)
    {
        if (is_null($billing_address_city)) {
            throw new \InvalidArgumentException('non-nullable billing_address_city cannot be null');
        }
        $this->container['billing_address_city'] = $billing_address_city;

        return $this;
    }

    /**
     * Gets billing_address_state
     *
     * @return string|null
     */
    public function getBillingAddressState()
    {
        return $this->container['billing_address_state'];
    }

    /**
     * Sets billing_address_state
     *
     * @param string|null $billing_address_state Billing address state.
     *
     * @return self
     */
    public function setBillingAddressState($billing_address_state)
    {
        if (is_null($billing_address_state)) {
            throw new \InvalidArgumentException('non-nullable billing_address_state cannot be null');
        }
        $this->container['billing_address_state'] = $billing_address_state;

        return $this;
    }

    /**
     * Gets billing_address_zip
     *
     * @return string|null
     */
    public function getBillingAddressZip()
    {
        return $this->container['billing_address_zip'];
    }

    /**
     * Sets billing_address_zip
     *
     * @param string|null $billing_address_zip Billing address ZIP code.
     *
     * @return self
     */
    public function setBillingAddressZip($billing_address_zip)
    {
        if (is_null($billing_address_zip)) {
            throw new \InvalidArgumentException('non-nullable billing_address_zip cannot be null');
        }
        $this->container['billing_address_zip'] = $billing_address_zip;

        return $this;
    }

    /**
     * Gets billing_address_country
     *
     * @return string|null
     */
    public function getBillingAddressCountry()
    {
        return $this->container['billing_address_country'];
    }

    /**
     * Sets billing_address_country
     *
     * @param string|null $billing_address_country Billing address country.
     *
     * @return self
     */
    public function setBillingAddressCountry($billing_address_country)
    {
        if (is_null($billing_address_country)) {
            throw new \InvalidArgumentException('non-nullable billing_address_country cannot be null');
        }
        $this->container['billing_address_country'] = $billing_address_country;

        return $this;
    }

    /**
     * Gets cpf_or_cnpj
     *
     * @return string
     */
    public function getCpfOrCnpj()
    {
        return $this->container['cpf_or_cnpj'];
    }

    /**
     * Sets cpf_or_cnpj
     *
     * @param string $cpf_or_cnpj Specify customer's CPF or CNPJ.
     *
     * @return self
     */
    public function setCpfOrCnpj($cpf_or_cnpj)
    {
        if (is_null($cpf_or_cnpj)) {
            throw new \InvalidArgumentException('non-nullable cpf_or_cnpj cannot be null');
        }
        $this->container['cpf_or_cnpj'] = $cpf_or_cnpj;

        return $this;
    }

    /**
     * Gets customer_ip
     *
     * @return string
     */
    public function getCustomerIp()
    {
        return $this->container['customer_ip'];
    }

    /**
     * Sets customer_ip
     *
     * @param string $customer_ip Specify customer's IPv4 or IPv6-formatted IP address of the customer.
     *
     * @return self
     */
    public function setCustomerIp($customer_ip)
    {
        if (is_null($customer_ip)) {
            throw new \InvalidArgumentException('non-nullable customer_ip cannot be null');
        }
        $this->container['customer_ip'] = $customer_ip;

        return $this;
    }

    /**
     * Gets corporate_card
     *
     * @return bool|null
     */
    public function getCorporateCard()
    {
        return $this->container['corporate_card'];
    }

    /**
     * Sets corporate_card
     *
     * @param bool|null $corporate_card Specify whether this payment card is a corporate card.
     *
     * @return self
     */
    public function setCorporateCard($corporate_card)
    {
        if (is_null($corporate_card)) {
            throw new \InvalidArgumentException('non-nullable corporate_card cannot be null');
        }
        $this->container['corporate_card'] = $corporate_card;

        return $this;
    }

    /**
     * Gets social_id
     *
     * @return \Komoju\Model\PaymentDetailsCreditCardKoreaSocialId|null
     */
    public function getSocialId()
    {
        return $this->container['social_id'];
    }

    /**
     * Sets social_id
     *
     * @param \Komoju\Model\PaymentDetailsCreditCardKoreaSocialId|null $social_id social_id
     *
     * @return self
     */
    public function setSocialId($social_id)
    {
        if (is_null($social_id)) {
            throw new \InvalidArgumentException('non-nullable social_id cannot be null');
        }
        $this->container['social_id'] = $social_id;

        return $this;
    }

    /**
     * Gets first_two_digits_of_pin
     *
     * @return string
     */
    public function getFirstTwoDigitsOfPin()
    {
        return $this->container['first_two_digits_of_pin'];
    }

    /**
     * Sets first_two_digits_of_pin
     *
     * @param string $first_two_digits_of_pin Specify the first four digit of credit card's PIN number.
     *
     * @return self
     */
    public function setFirstTwoDigitsOfPin($first_two_digits_of_pin)
    {
        if (is_null($first_two_digits_of_pin)) {
            throw new \InvalidArgumentException('non-nullable first_two_digits_of_pin cannot be null');
        }
        if ((mb_strlen($first_two_digits_of_pin) > 2)) {
            throw new \InvalidArgumentException('invalid length for $first_two_digits_of_pin when calling PaymentDetailsAll., must be smaller than or equal to 2.');
        }
        if ((mb_strlen($first_two_digits_of_pin) < 2)) {
            throw new \InvalidArgumentException('invalid length for $first_two_digits_of_pin when calling PaymentDetailsAll., must be bigger than or equal to 2.');
        }

        $this->container['first_two_digits_of_pin'] = $first_two_digits_of_pin;

        return $this;
    }

    /**
     * Gets sequence_number
     *
     * @return string|null
     */
    public function getSequenceNumber()
    {
        return $this->container['sequence_number'];
    }

    /**
     * Sets sequence_number
     *
     * @param string|null $sequence_number Specify the sequence number from the credit card terminal
     *
     * @return self
     */
    public function setSequenceNumber($sequence_number)
    {
        if (is_null($sequence_number)) {
            throw new \InvalidArgumentException('non-nullable sequence_number cannot be null');
        }
        $this->container['sequence_number'] = $sequence_number;

        return $this;
    }

    /**
     * Gets field55
     *
     * @return string|null
     */
    public function getField55()
    {
        return $this->container['field55'];
    }

    /**
     * Sets field55
     *
     * @param string|null $field55 Specify the EMV data produced by the terminal.
     *
     * @return self
     */
    public function setField55($field55)
    {
        if (is_null($field55)) {
            throw new \InvalidArgumentException('non-nullable field55 cannot be null');
        }
        $this->container['field55'] = $field55;

        return $this;
    }

    /**
     * Gets pos_data_code
     *
     * @return string|null
     */
    public function getPosDataCode()
    {
        return $this->container['pos_data_code'];
    }

    /**
     * Sets pos_data_code
     *
     * @param string|null $pos_data_code Specify the POS data code produced by the terminal.
     *
     * @return self
     */
    public function setPosDataCode($pos_data_code)
    {
        if (is_null($pos_data_code)) {
            throw new \InvalidArgumentException('non-nullable pos_data_code cannot be null');
        }
        $this->container['pos_data_code'] = $pos_data_code;

        return $this;
    }

    /**
     * Gets track2
     *
     * @return string|null
     */
    public function getTrack2()
    {
        return $this->container['track2'];
    }

    /**
     * Sets track2
     *
     * @param string|null $track2 Specify the data read from track 2 of the payment card.
     *
     * @return self
     */
    public function setTrack2($track2)
    {
        if (is_null($track2)) {
            throw new \InvalidArgumentException('non-nullable track2 cannot be null');
        }
        $this->container['track2'] = $track2;

        return $this;
    }

    /**
     * Gets flow_type
     *
     * @return string|null
     */
    public function getFlowType()
    {
        return $this->container['flow_type'];
    }

    /**
     * Sets flow_type
     *
     * @param string|null $flow_type Specify whether this transaction is a EMV or magnetic stripe transaction.  - Use value \"1\" for EMV transaction. - Use value \"2\" for magnetic stripe transaction.
     *
     * @return self
     */
    public function setFlowType($flow_type)
    {
        if (is_null($flow_type)) {
            throw new \InvalidArgumentException('non-nullable flow_type cannot be null');
        }
        $this->container['flow_type'] = $flow_type;

        return $this;
    }

    /**
     * Gets scanned_code
     *
     * @return string|null
     */
    public function getScannedCode()
    {
        return $this->container['scanned_code'];
    }

    /**
     * Sets scanned_code
     *
     * @param string|null $scanned_code scanned_code
     *
     * @return self
     */
    public function setScannedCode($scanned_code)
    {
        if (is_null($scanned_code)) {
            throw new \InvalidArgumentException('non-nullable scanned_code cannot be null');
        }
        $this->container['scanned_code'] = $scanned_code;

        return $this;
    }

    /**
     * Gets phone
     *
     * @return string
     */
    public function getPhone()
    {
        return $this->container['phone'];
    }

    /**
     * Sets phone
     *
     * @param string $phone Customer's phone number
     *
     * @return self
     */
    public function setPhone($phone)
    {
        if (is_null($phone)) {
            throw new \InvalidArgumentException('non-nullable phone cannot be null');
        }

        if ((!preg_match("/\\A([() \\-_+]*[0-9]){10}[() \\-_+0-9]*\\Z/", ObjectSerializer::toString($phone)))) {
            throw new \InvalidArgumentException("invalid value for \$phone when calling PaymentDetailsAll., must conform to the pattern /\\A([() \\-_+]*[0-9]){10}[() \\-_+0-9]*\\Z/.");
        }

        $this->container['phone'] = $phone;

        return $this;
    }

    /**
     * Gets given_name_kana
     *
     * @return string
     */
    public function getGivenNameKana()
    {
        return $this->container['given_name_kana'];
    }

    /**
     * Sets given_name_kana
     *
     * @param string $given_name_kana Given name of the customer, written in katakana characters.
     *
     * @return self
     */
    public function setGivenNameKana($given_name_kana)
    {
        if (is_null($given_name_kana)) {
            throw new \InvalidArgumentException('non-nullable given_name_kana cannot be null');
        }
        if ((mb_strlen($given_name_kana) > 255)) {
            throw new \InvalidArgumentException('invalid length for $given_name_kana when calling PaymentDetailsAll., must be smaller than or equal to 255.');
        }

        $this->container['given_name_kana'] = $given_name_kana;

        return $this;
    }

    /**
     * Gets family_name_kana
     *
     * @return string
     */
    public function getFamilyNameKana()
    {
        return $this->container['family_name_kana'];
    }

    /**
     * Sets family_name_kana
     *
     * @param string $family_name_kana Family name of the customer, written in katakana characters.
     *
     * @return self
     */
    public function setFamilyNameKana($family_name_kana)
    {
        if (is_null($family_name_kana)) {
            throw new \InvalidArgumentException('non-nullable family_name_kana cannot be null');
        }
        if ((mb_strlen($family_name_kana) > 255)) {
            throw new \InvalidArgumentException('invalid length for $family_name_kana when calling PaymentDetailsAll., must be smaller than or equal to 255.');
        }

        $this->container['family_name_kana'] = $family_name_kana;

        return $this;
    }

    /**
     * Gets prepaid_number
     *
     * @return string
     */
    public function getPrepaidNumber()
    {
        return $this->container['prepaid_number'];
    }

    /**
     * Sets prepaid_number
     *
     * @param string $prepaid_number Prepaid card number.
     *
     * @return self
     */
    public function setPrepaidNumber($prepaid_number)
    {
        if (is_null($prepaid_number)) {
            throw new \InvalidArgumentException('non-nullable prepaid_number cannot be null');
        }
        if ((mb_strlen($prepaid_number) > 16)) {
            throw new \InvalidArgumentException('invalid length for $prepaid_number when calling PaymentDetailsAll., must be smaller than or equal to 16.');
        }
        if ((mb_strlen($prepaid_number) < 16)) {
            throw new \InvalidArgumentException('invalid length for $prepaid_number when calling PaymentDetailsAll., must be bigger than or equal to 16.');
        }

        $this->container['prepaid_number'] = $prepaid_number;

        return $this;
    }

    /**
     * Gets culture_id
     *
     * @return string
     */
    public function getCultureId()
    {
        return $this->container['culture_id'];
    }

    /**
     * Sets culture_id
     *
     * @param string $culture_id Culture Land ID.
     *
     * @return self
     */
    public function setCultureId($culture_id)
    {
        if (is_null($culture_id)) {
            throw new \InvalidArgumentException('non-nullable culture_id cannot be null');
        }
        if ((mb_strlen($culture_id) > 12)) {
            throw new \InvalidArgumentException('invalid length for $culture_id when calling PaymentDetailsAll., must be smaller than or equal to 12.');
        }
        if ((mb_strlen($culture_id) < 1)) {
            throw new \InvalidArgumentException('invalid length for $culture_id when calling PaymentDetailsAll., must be bigger than or equal to 1.');
        }

        $this->container['culture_id'] = $culture_id;

        return $this;
    }

    /**
     * Gets culture_password
     *
     * @return string
     */
    public function getCulturePassword()
    {
        return $this->container['culture_password'];
    }

    /**
     * Sets culture_password
     *
     * @param string $culture_password Culture Land password.
     *
     * @return self
     */
    public function setCulturePassword($culture_password)
    {
        if (is_null($culture_password)) {
            throw new \InvalidArgumentException('non-nullable culture_password cannot be null');
        }
        if ((mb_strlen($culture_password) > 20)) {
            throw new \InvalidArgumentException('invalid length for $culture_password when calling PaymentDetailsAll., must be smaller than or equal to 20.');
        }
        if ((mb_strlen($culture_password) < 1)) {
            throw new \InvalidArgumentException('invalid length for $culture_password when calling PaymentDetailsAll., must be bigger than or equal to 1.');
        }

        $this->container['culture_password'] = $culture_password;

        return $this;
    }

    /**
     * Gets user_no
     *
     * @return string
     */
    public function getUserNo()
    {
        return $this->container['user_no'];
    }

    /**
     * Sets user_no
     *
     * @param string $user_no Dospara user number.
     *
     * @return self
     */
    public function setUserNo($user_no)
    {
        if (is_null($user_no)) {
            throw new \InvalidArgumentException('non-nullable user_no cannot be null');
        }
        if ((mb_strlen($user_no) > 20)) {
            throw new \InvalidArgumentException('invalid length for $user_no when calling PaymentDetailsAll., must be smaller than or equal to 20.');
        }

        $this->container['user_no'] = $user_no;

        return $this;
    }

    /**
     * Gets user_password
     *
     * @return string
     */
    public function getUserPassword()
    {
        return $this->container['user_password'];
    }

    /**
     * Sets user_password
     *
     * @param string $user_password Dospara user password.
     *
     * @return self
     */
    public function setUserPassword($user_password)
    {
        if (is_null($user_password)) {
            throw new \InvalidArgumentException('non-nullable user_password cannot be null');
        }
        if ((mb_strlen($user_password) > 20)) {
            throw new \InvalidArgumentException('invalid length for $user_password when calling PaymentDetailsAll., must be smaller than or equal to 20.');
        }

        $this->container['user_password'] = $user_password;

        return $this;
    }

    /**
     * Gets happy_money_id
     *
     * @return string
     */
    public function getHappyMoneyId()
    {
        return $this->container['happy_money_id'];
    }

    /**
     * Sets happy_money_id
     *
     * @param string $happy_money_id Happy Money ID.
     *
     * @return self
     */
    public function setHappyMoneyId($happy_money_id)
    {
        if (is_null($happy_money_id)) {
            throw new \InvalidArgumentException('non-nullable happy_money_id cannot be null');
        }
        if ((mb_strlen($happy_money_id) > 20)) {
            throw new \InvalidArgumentException('invalid length for $happy_money_id when calling PaymentDetailsAll., must be smaller than or equal to 20.');
        }
        if ((mb_strlen($happy_money_id) < 1)) {
            throw new \InvalidArgumentException('invalid length for $happy_money_id when calling PaymentDetailsAll., must be bigger than or equal to 1.');
        }

        $this->container['happy_money_id'] = $happy_money_id;

        return $this;
    }

    /**
     * Gets happy_money_password
     *
     * @return string
     */
    public function getHappyMoneyPassword()
    {
        return $this->container['happy_money_password'];
    }

    /**
     * Sets happy_money_password
     *
     * @param string $happy_money_password Happy Money password.
     *
     * @return self
     */
    public function setHappyMoneyPassword($happy_money_password)
    {
        if (is_null($happy_money_password)) {
            throw new \InvalidArgumentException('non-nullable happy_money_password cannot be null');
        }
        if ((mb_strlen($happy_money_password) > 50)) {
            throw new \InvalidArgumentException('invalid length for $happy_money_password when calling PaymentDetailsAll., must be smaller than or equal to 50.');
        }
        if ((mb_strlen($happy_money_password) < 1)) {
            throw new \InvalidArgumentException('invalid length for $happy_money_password when calling PaymentDetailsAll., must be bigger than or equal to 1.');
        }

        $this->container['happy_money_password'] = $happy_money_password;

        return $this;
    }

    /**
     * Gets store
     *
     * @return string
     */
    public function getStore()
    {
        return $this->container['store'];
    }

    /**
     * Sets store
     *
     * @param string $store Specify the name of convenience store user will make payment from.
     *
     * @return self
     */
    public function setStore($store)
    {
        if (is_null($store)) {
            throw new \InvalidArgumentException('non-nullable store cannot be null');
        }
        $this->container['store'] = $store;

        return $this;
    }

    /**
     * Gets brand
     *
     * @return string
     */
    public function getBrand()
    {
        return $this->container['brand'];
    }

    /**
     * Sets brand
     *
     * @param string $brand Specify the carrier.
     *
     * @return self
     */
    public function setBrand($brand)
    {
        if (is_null($brand)) {
            throw new \InvalidArgumentException('non-nullable brand cannot be null');
        }
        $this->container['brand'] = $brand;

        return $this;
    }

    /**
     * Gets customer_age
     *
     * @return int|null
     */
    public function getCustomerAge()
    {
        return $this->container['customer_age'];
    }

    /**
     * Sets customer_age
     *
     * @param int|null $customer_age customer_age
     *
     * @return self
     */
    public function setCustomerAge($customer_age)
    {
        if (is_null($customer_age)) {
            throw new \InvalidArgumentException('non-nullable customer_age cannot be null');
        }
        $this->container['customer_age'] = $customer_age;

        return $this;
    }

    /**
     * Gets customer_last_order_amount
     *
     * @return int|null
     */
    public function getCustomerLastOrderAmount()
    {
        return $this->container['customer_last_order_amount'];
    }

    /**
     * Sets customer_last_order_amount
     *
     * @param int|null $customer_last_order_amount customer_last_order_amount
     *
     * @return self
     */
    public function setCustomerLastOrderAmount($customer_last_order_amount)
    {
        if (is_null($customer_last_order_amount)) {
            throw new \InvalidArgumentException('non-nullable customer_last_order_amount cannot be null');
        }
        $this->container['customer_last_order_amount'] = $customer_last_order_amount;

        return $this;
    }

    /**
     * Gets customer_last_order_at
     *
     * @return int|null
     */
    public function getCustomerLastOrderAt()
    {
        return $this->container['customer_last_order_at'];
    }

    /**
     * Sets customer_last_order_at
     *
     * @param int|null $customer_last_order_at customer_last_order_at
     *
     * @return self
     */
    public function setCustomerLastOrderAt($customer_last_order_at)
    {
        if (is_null($customer_last_order_at)) {
            throw new \InvalidArgumentException('non-nullable customer_last_order_at cannot be null');
        }
        $this->container['customer_last_order_at'] = $customer_last_order_at;

        return $this;
    }

    /**
     * Gets customer_lifetime_value
     *
     * @return int|null
     */
    public function getCustomerLifetimeValue()
    {
        return $this->container['customer_lifetime_value'];
    }

    /**
     * Sets customer_lifetime_value
     *
     * @param int|null $customer_lifetime_value customer_lifetime_value
     *
     * @return self
     */
    public function setCustomerLifetimeValue($customer_lifetime_value)
    {
        if (is_null($customer_lifetime_value)) {
            throw new \InvalidArgumentException('non-nullable customer_lifetime_value cannot be null');
        }
        $this->container['customer_lifetime_value'] = $customer_lifetime_value;

        return $this;
    }

    /**
     * Gets customer_name
     *
     * @return string
     */
    public function getCustomerName()
    {
        return $this->container['customer_name'];
    }

    /**
     * Sets customer_name
     *
     * @param string $customer_name customer_name
     *
     * @return self
     */
    public function setCustomerName($customer_name)
    {
        if (is_null($customer_name)) {
            throw new \InvalidArgumentException('non-nullable customer_name cannot be null');
        }
        $this->container['customer_name'] = $customer_name;

        return $this;
    }

    /**
     * Gets customer_order_count
     *
     * @return int|null
     */
    public function getCustomerOrderCount()
    {
        return $this->container['customer_order_count'];
    }

    /**
     * Sets customer_order_count
     *
     * @param int|null $customer_order_count customer_order_count
     *
     * @return self
     */
    public function setCustomerOrderCount($customer_order_count)
    {
        if (is_null($customer_order_count)) {
            throw new \InvalidArgumentException('non-nullable customer_order_count cannot be null');
        }
        $this->container['customer_order_count'] = $customer_order_count;

        return $this;
    }

    /**
     * Gets external_customer_id
     *
     * @return string|null
     */
    public function getExternalCustomerId()
    {
        return $this->container['external_customer_id'];
    }

    /**
     * Sets external_customer_id
     *
     * @param string|null $external_customer_id external_customer_id
     *
     * @return self
     */
    public function setExternalCustomerId($external_customer_id)
    {
        if (is_null($external_customer_id)) {
            throw new \InvalidArgumentException('non-nullable external_customer_id cannot be null');
        }
        $this->container['external_customer_id'] = $external_customer_id;

        return $this;
    }

    /**
     * Gets item_title
     *
     * @return string|null
     */
    public function getItemTitle()
    {
        return $this->container['item_title'];
    }

    /**
     * Sets item_title
     *
     * @param string|null $item_title item_title
     *
     * @return self
     */
    public function setItemTitle($item_title)
    {
        if (is_null($item_title)) {
            throw new \InvalidArgumentException('non-nullable item_title cannot be null');
        }
        $this->container['item_title'] = $item_title;

        return $this;
    }

    /**
     * Gets customer_name_kana
     *
     * @return string|null
     */
    public function getCustomerNameKana()
    {
        return $this->container['customer_name_kana'];
    }

    /**
     * Sets customer_name_kana
     *
     * @param string|null $customer_name_kana customer_name_kana
     *
     * @return self
     */
    public function setCustomerNameKana($customer_name_kana)
    {
        if (is_null($customer_name_kana)) {
            throw new \InvalidArgumentException('non-nullable customer_name_kana cannot be null');
        }
        $this->container['customer_name_kana'] = $customer_name_kana;

        return $this;
    }

    /**
     * Gets capture
     *
     * @return bool|null
     */
    public function getCapture()
    {
        return $this->container['capture'];
    }

    /**
     * Sets capture
     *
     * @param bool|null $capture capture
     *
     * @return self
     */
    public function setCapture($capture)
    {
        if (is_null($capture)) {
            throw new \InvalidArgumentException('non-nullable capture cannot be null');
        }
        $this->container['capture'] = $capture;

        return $this;
    }

    /**
     * Gets user_authorization_id
     *
     * @return string|null
     */
    public function getUserAuthorizationId()
    {
        return $this->container['user_authorization_id'];
    }

    /**
     * Sets user_authorization_id
     *
     * @param string|null $user_authorization_id user_authorization_id
     *
     * @return self
     */
    public function setUserAuthorizationId($user_authorization_id)
    {
        if (is_null($user_authorization_id)) {
            throw new \InvalidArgumentException('non-nullable user_authorization_id cannot be null');
        }
        $this->container['user_authorization_id'] = $user_authorization_id;

        return $this;
    }

    /**
     * Gets cpf
     *
     * @return string
     */
    public function getCpf()
    {
        return $this->container['cpf'];
    }

    /**
     * Sets cpf
     *
     * @param string $cpf Customer's CPF number
     *
     * @return self
     */
    public function setCpf($cpf)
    {
        if (is_null($cpf)) {
            throw new \InvalidArgumentException('non-nullable cpf cannot be null');
        }

        if ((!preg_match("/([0-9]{3}[.]?[0-9]{3}[.]?[0-9]{3}[-]?[0-9]{2})/", ObjectSerializer::toString($cpf)))) {
            throw new \InvalidArgumentException("invalid value for \$cpf when calling PaymentDetailsAll., must conform to the pattern /([0-9]{3}[.]?[0-9]{3}[.]?[0-9]{3}[-]?[0-9]{2})/.");
        }

        $this->container['cpf'] = $cpf;

        return $this;
    }

    /**
     * Gets birthday
     *
     * @return string
     */
    public function getBirthday()
    {
        return $this->container['birthday'];
    }

    /**
     * Sets birthday
     *
     * @param string $birthday Customer's date of birth in `YYMMDD` format.
     *
     * @return self
     */
    public function setBirthday($birthday)
    {
        if (is_null($birthday)) {
            throw new \InvalidArgumentException('non-nullable birthday cannot be null');
        }
        if ((mb_strlen($birthday) > 6)) {
            throw new \InvalidArgumentException('invalid length for $birthday when calling PaymentDetailsAll., must be smaller than or equal to 6.');
        }
        if ((mb_strlen($birthday) < 6)) {
            throw new \InvalidArgumentException('invalid length for $birthday when calling PaymentDetailsAll., must be bigger than or equal to 6.');
        }

        $this->container['birthday'] = $birthday;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


