<?php
/**
 * RefundRequest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Komoju
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * KOMOJU API
 *
 * Full featured access to the KOMOJU payments system.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.23.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Komoju\Model;

use \ArrayAccess;
use \Komoju\ObjectSerializer;

/**
 * RefundRequest Class Doc Comment
 *
 * @category Class
 * @package  Komoju
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class RefundRequest implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'RefundRequest';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'id' => 'string',
        'payment' => 'string',
        'customer_name' => 'string',
        'bank_name' => 'string',
        'bank_code' => 'string',
        'branch_name' => 'string',
        'branch_number' => 'string',
        'account_number' => 'string',
        'description' => 'string',
        'status' => '\Komoju\Model\RefundRequestStatus',
        'created_at' => '\DateTime',
        'platform_details' => '\Komoju\Model\PlatformDetails'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'id' => null,
        'payment' => null,
        'customer_name' => null,
        'bank_name' => null,
        'bank_code' => null,
        'branch_name' => null,
        'branch_number' => null,
        'account_number' => null,
        'description' => null,
        'status' => null,
        'created_at' => 'date-time',
        'platform_details' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'id' => false,
        'payment' => false,
        'customer_name' => false,
        'bank_name' => false,
        'bank_code' => false,
        'branch_name' => false,
        'branch_number' => false,
        'account_number' => false,
        'description' => false,
        'status' => false,
        'created_at' => false,
        'platform_details' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'payment' => 'payment',
        'customer_name' => 'customer_name',
        'bank_name' => 'bank_name',
        'bank_code' => 'bank_code',
        'branch_name' => 'branch_name',
        'branch_number' => 'branch_number',
        'account_number' => 'account_number',
        'description' => 'description',
        'status' => 'status',
        'created_at' => 'created_at',
        'platform_details' => 'platform_details'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'payment' => 'setPayment',
        'customer_name' => 'setCustomerName',
        'bank_name' => 'setBankName',
        'bank_code' => 'setBankCode',
        'branch_name' => 'setBranchName',
        'branch_number' => 'setBranchNumber',
        'account_number' => 'setAccountNumber',
        'description' => 'setDescription',
        'status' => 'setStatus',
        'created_at' => 'setCreatedAt',
        'platform_details' => 'setPlatformDetails'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'payment' => 'getPayment',
        'customer_name' => 'getCustomerName',
        'bank_name' => 'getBankName',
        'bank_code' => 'getBankCode',
        'branch_name' => 'getBranchName',
        'branch_number' => 'getBranchNumber',
        'account_number' => 'getAccountNumber',
        'description' => 'getDescription',
        'status' => 'getStatus',
        'created_at' => 'getCreatedAt',
        'platform_details' => 'getPlatformDetails'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('payment', $data ?? [], null);
        $this->setIfExists('customer_name', $data ?? [], null);
        $this->setIfExists('bank_name', $data ?? [], null);
        $this->setIfExists('bank_code', $data ?? [], null);
        $this->setIfExists('branch_name', $data ?? [], null);
        $this->setIfExists('branch_number', $data ?? [], null);
        $this->setIfExists('account_number', $data ?? [], null);
        $this->setIfExists('description', $data ?? [], null);
        $this->setIfExists('status', $data ?? [], null);
        $this->setIfExists('created_at', $data ?? [], null);
        $this->setIfExists('platform_details', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['id'] === null) {
            $invalidProperties[] = "'id' can't be null";
        }
        if ((mb_strlen($this->container['id']) > 25)) {
            $invalidProperties[] = "invalid value for 'id', the character length must be smaller than or equal to 25.";
        }

        if ((mb_strlen($this->container['id']) < 25)) {
            $invalidProperties[] = "invalid value for 'id', the character length must be bigger than or equal to 25.";
        }

        if ($this->container['payment'] === null) {
            $invalidProperties[] = "'payment' can't be null";
        }
        if ((mb_strlen($this->container['payment']) > 25)) {
            $invalidProperties[] = "invalid value for 'payment', the character length must be smaller than or equal to 25.";
        }

        if ((mb_strlen($this->container['payment']) < 25)) {
            $invalidProperties[] = "invalid value for 'payment', the character length must be bigger than or equal to 25.";
        }

        if ($this->container['customer_name'] === null) {
            $invalidProperties[] = "'customer_name' can't be null";
        }
        if ($this->container['bank_name'] === null) {
            $invalidProperties[] = "'bank_name' can't be null";
        }
        if ($this->container['bank_code'] === null) {
            $invalidProperties[] = "'bank_code' can't be null";
        }
        if ((mb_strlen($this->container['bank_code']) > 4)) {
            $invalidProperties[] = "invalid value for 'bank_code', the character length must be smaller than or equal to 4.";
        }

        if ((mb_strlen($this->container['bank_code']) < 4)) {
            $invalidProperties[] = "invalid value for 'bank_code', the character length must be bigger than or equal to 4.";
        }

        if ($this->container['branch_name'] === null) {
            $invalidProperties[] = "'branch_name' can't be null";
        }
        if ($this->container['branch_number'] === null) {
            $invalidProperties[] = "'branch_number' can't be null";
        }
        if ((mb_strlen($this->container['branch_number']) > 3)) {
            $invalidProperties[] = "invalid value for 'branch_number', the character length must be smaller than or equal to 3.";
        }

        if ((mb_strlen($this->container['branch_number']) < 3)) {
            $invalidProperties[] = "invalid value for 'branch_number', the character length must be bigger than or equal to 3.";
        }

        if ($this->container['account_number'] === null) {
            $invalidProperties[] = "'account_number' can't be null";
        }
        if ((mb_strlen($this->container['account_number']) > 7)) {
            $invalidProperties[] = "invalid value for 'account_number', the character length must be smaller than or equal to 7.";
        }

        if ((mb_strlen($this->container['account_number']) < 7)) {
            $invalidProperties[] = "invalid value for 'account_number', the character length must be bigger than or equal to 7.";
        }

        if ($this->container['status'] === null) {
            $invalidProperties[] = "'status' can't be null";
        }
        if ($this->container['created_at'] === null) {
            $invalidProperties[] = "'created_at' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return string
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string $id A unique 25-character alphanumeric refund request identifier.
     *
     * @return self
     */
    public function setId($id)
    {
        if (is_null($id)) {
            throw new \InvalidArgumentException('non-nullable id cannot be null');
        }
        if ((mb_strlen($id) > 25)) {
            throw new \InvalidArgumentException('invalid length for $id when calling RefundRequest., must be smaller than or equal to 25.');
        }
        if ((mb_strlen($id) < 25)) {
            throw new \InvalidArgumentException('invalid length for $id when calling RefundRequest., must be bigger than or equal to 25.');
        }

        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets payment
     *
     * @return string
     */
    public function getPayment()
    {
        return $this->container['payment'];
    }

    /**
     * Sets payment
     *
     * @param string $payment A unique 25-character alphanumeric payment identifier.
     *
     * @return self
     */
    public function setPayment($payment)
    {
        if (is_null($payment)) {
            throw new \InvalidArgumentException('non-nullable payment cannot be null');
        }
        if ((mb_strlen($payment) > 25)) {
            throw new \InvalidArgumentException('invalid length for $payment when calling RefundRequest., must be smaller than or equal to 25.');
        }
        if ((mb_strlen($payment) < 25)) {
            throw new \InvalidArgumentException('invalid length for $payment when calling RefundRequest., must be bigger than or equal to 25.');
        }

        $this->container['payment'] = $payment;

        return $this;
    }

    /**
     * Gets customer_name
     *
     * @return string
     */
    public function getCustomerName()
    {
        return $this->container['customer_name'];
    }

    /**
     * Sets customer_name
     *
     * @param string $customer_name Customer's name in half-width katakana characters.
     *
     * @return self
     */
    public function setCustomerName($customer_name)
    {
        if (is_null($customer_name)) {
            throw new \InvalidArgumentException('non-nullable customer_name cannot be null');
        }
        $this->container['customer_name'] = $customer_name;

        return $this;
    }

    /**
     * Gets bank_name
     *
     * @return string
     */
    public function getBankName()
    {
        return $this->container['bank_name'];
    }

    /**
     * Sets bank_name
     *
     * @param string $bank_name The name of the bank that customer would like money to be deposited to.
     *
     * @return self
     */
    public function setBankName($bank_name)
    {
        if (is_null($bank_name)) {
            throw new \InvalidArgumentException('non-nullable bank_name cannot be null');
        }
        $this->container['bank_name'] = $bank_name;

        return $this;
    }

    /**
     * Gets bank_code
     *
     * @return string
     */
    public function getBankCode()
    {
        return $this->container['bank_code'];
    }

    /**
     * Sets bank_code
     *
     * @param string $bank_code 4-digit bank code. May be `null` if it's not given.
     *
     * @return self
     */
    public function setBankCode($bank_code)
    {
        if (is_null($bank_code)) {
            throw new \InvalidArgumentException('non-nullable bank_code cannot be null');
        }
        if ((mb_strlen($bank_code) > 4)) {
            throw new \InvalidArgumentException('invalid length for $bank_code when calling RefundRequest., must be smaller than or equal to 4.');
        }
        if ((mb_strlen($bank_code) < 4)) {
            throw new \InvalidArgumentException('invalid length for $bank_code when calling RefundRequest., must be bigger than or equal to 4.');
        }

        $this->container['bank_code'] = $bank_code;

        return $this;
    }

    /**
     * Gets branch_name
     *
     * @return string
     */
    public function getBranchName()
    {
        return $this->container['branch_name'];
    }

    /**
     * Sets branch_name
     *
     * @param string $branch_name The name of the branch.
     *
     * @return self
     */
    public function setBranchName($branch_name)
    {
        if (is_null($branch_name)) {
            throw new \InvalidArgumentException('non-nullable branch_name cannot be null');
        }
        $this->container['branch_name'] = $branch_name;

        return $this;
    }

    /**
     * Gets branch_number
     *
     * @return string
     */
    public function getBranchNumber()
    {
        return $this->container['branch_number'];
    }

    /**
     * Sets branch_number
     *
     * @param string $branch_number 3-digit branch number.
     *
     * @return self
     */
    public function setBranchNumber($branch_number)
    {
        if (is_null($branch_number)) {
            throw new \InvalidArgumentException('non-nullable branch_number cannot be null');
        }
        if ((mb_strlen($branch_number) > 3)) {
            throw new \InvalidArgumentException('invalid length for $branch_number when calling RefundRequest., must be smaller than or equal to 3.');
        }
        if ((mb_strlen($branch_number) < 3)) {
            throw new \InvalidArgumentException('invalid length for $branch_number when calling RefundRequest., must be bigger than or equal to 3.');
        }

        $this->container['branch_number'] = $branch_number;

        return $this;
    }

    /**
     * Gets account_number
     *
     * @return string
     */
    public function getAccountNumber()
    {
        return $this->container['account_number'];
    }

    /**
     * Sets account_number
     *
     * @param string $account_number 7-digit account number.
     *
     * @return self
     */
    public function setAccountNumber($account_number)
    {
        if (is_null($account_number)) {
            throw new \InvalidArgumentException('non-nullable account_number cannot be null');
        }
        if ((mb_strlen($account_number) > 7)) {
            throw new \InvalidArgumentException('invalid length for $account_number when calling RefundRequest., must be smaller than or equal to 7.');
        }
        if ((mb_strlen($account_number) < 7)) {
            throw new \InvalidArgumentException('invalid length for $account_number when calling RefundRequest., must be bigger than or equal to 7.');
        }

        $this->container['account_number'] = $account_number;

        return $this;
    }

    /**
     * Gets description
     *
     * @return string|null
     */
    public function getDescription()
    {
        return $this->container['description'];
    }

    /**
     * Sets description
     *
     * @param string|null $description Optional description or reason for this refund request.
     *
     * @return self
     */
    public function setDescription($description)
    {
        if (is_null($description)) {
            throw new \InvalidArgumentException('non-nullable description cannot be null');
        }
        $this->container['description'] = $description;

        return $this;
    }

    /**
     * Gets status
     *
     * @return \Komoju\Model\RefundRequestStatus
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param \Komoju\Model\RefundRequestStatus $status status
     *
     * @return self
     */
    public function setStatus($status)
    {
        if (is_null($status)) {
            throw new \InvalidArgumentException('non-nullable status cannot be null');
        }
        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets created_at
     *
     * @return \DateTime
     */
    public function getCreatedAt()
    {
        return $this->container['created_at'];
    }

    /**
     * Sets created_at
     *
     * @param \DateTime $created_at Timestamp when the refund request was created.
     *
     * @return self
     */
    public function setCreatedAt($created_at)
    {
        if (is_null($created_at)) {
            throw new \InvalidArgumentException('non-nullable created_at cannot be null');
        }
        $this->container['created_at'] = $created_at;

        return $this;
    }

    /**
     * Gets platform_details
     *
     * @return \Komoju\Model\PlatformDetails|null
     */
    public function getPlatformDetails()
    {
        return $this->container['platform_details'];
    }

    /**
     * Sets platform_details
     *
     * @param \Komoju\Model\PlatformDetails|null $platform_details platform_details
     *
     * @return self
     */
    public function setPlatformDetails($platform_details)
    {
        if (is_null($platform_details)) {
            throw new \InvalidArgumentException('non-nullable platform_details cannot be null');
        }
        $this->container['platform_details'] = $platform_details;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


