<?php
/**
 * ResponsePaymentDetailsCreditCardTerminal
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Komoju
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * KOMOJU API
 *
 * Full featured access to the KOMOJU payments system.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.23.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Komoju\Model;

use \ArrayAccess;
use \Komoju\ObjectSerializer;

/**
 * ResponsePaymentDetailsCreditCardTerminal Class Doc Comment
 *
 * @category Class
 * @description 
 * @package  Komoju
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class ResponsePaymentDetailsCreditCardTerminal implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'ResponsePaymentDetailsCreditCardTerminal';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'type' => 'string',
        'brand' => 'string',
        'last_four_digits' => 'string',
        'month' => 'int',
        'year' => 'int',
        'field55' => 'string',
        'cardnet_status' => 'string',
        'approval_number' => 'string',
        'shipping_address_name' => 'string',
        'shipping_address_line1' => 'string',
        'shipping_address_line2' => 'string',
        'shipping_address_city' => 'string',
        'shipping_address_state' => 'string',
        'shipping_address_zip' => 'string',
        'shipping_address_country' => 'string',
        'billing_address_name' => 'string',
        'billing_address_line1' => 'string',
        'billing_address_line2' => 'string',
        'billing_address_city' => 'string',
        'billing_address_state' => 'string',
        'billing_address_zip' => 'string',
        'billing_address_country' => 'string'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'type' => null,
        'brand' => null,
        'last_four_digits' => null,
        'month' => 'int32',
        'year' => 'int32',
        'field55' => null,
        'cardnet_status' => null,
        'approval_number' => null,
        'shipping_address_name' => null,
        'shipping_address_line1' => null,
        'shipping_address_line2' => null,
        'shipping_address_city' => null,
        'shipping_address_state' => null,
        'shipping_address_zip' => null,
        'shipping_address_country' => null,
        'billing_address_name' => null,
        'billing_address_line1' => null,
        'billing_address_line2' => null,
        'billing_address_city' => null,
        'billing_address_state' => null,
        'billing_address_zip' => null,
        'billing_address_country' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'type' => false,
        'brand' => false,
        'last_four_digits' => false,
        'month' => false,
        'year' => false,
        'field55' => false,
        'cardnet_status' => false,
        'approval_number' => false,
        'shipping_address_name' => false,
        'shipping_address_line1' => false,
        'shipping_address_line2' => false,
        'shipping_address_city' => false,
        'shipping_address_state' => false,
        'shipping_address_zip' => false,
        'shipping_address_country' => false,
        'billing_address_name' => false,
        'billing_address_line1' => false,
        'billing_address_line2' => false,
        'billing_address_city' => false,
        'billing_address_state' => false,
        'billing_address_zip' => false,
        'billing_address_country' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'type' => 'type',
        'brand' => 'brand',
        'last_four_digits' => 'last_four_digits',
        'month' => 'month',
        'year' => 'year',
        'field55' => 'field55',
        'cardnet_status' => 'cardnet_status',
        'approval_number' => 'approval_number',
        'shipping_address_name' => 'shipping_address_name',
        'shipping_address_line1' => 'shipping_address_line1',
        'shipping_address_line2' => 'shipping_address_line2',
        'shipping_address_city' => 'shipping_address_city',
        'shipping_address_state' => 'shipping_address_state',
        'shipping_address_zip' => 'shipping_address_zip',
        'shipping_address_country' => 'shipping_address_country',
        'billing_address_name' => 'billing_address_name',
        'billing_address_line1' => 'billing_address_line1',
        'billing_address_line2' => 'billing_address_line2',
        'billing_address_city' => 'billing_address_city',
        'billing_address_state' => 'billing_address_state',
        'billing_address_zip' => 'billing_address_zip',
        'billing_address_country' => 'billing_address_country'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'type' => 'setType',
        'brand' => 'setBrand',
        'last_four_digits' => 'setLastFourDigits',
        'month' => 'setMonth',
        'year' => 'setYear',
        'field55' => 'setField55',
        'cardnet_status' => 'setCardnetStatus',
        'approval_number' => 'setApprovalNumber',
        'shipping_address_name' => 'setShippingAddressName',
        'shipping_address_line1' => 'setShippingAddressLine1',
        'shipping_address_line2' => 'setShippingAddressLine2',
        'shipping_address_city' => 'setShippingAddressCity',
        'shipping_address_state' => 'setShippingAddressState',
        'shipping_address_zip' => 'setShippingAddressZip',
        'shipping_address_country' => 'setShippingAddressCountry',
        'billing_address_name' => 'setBillingAddressName',
        'billing_address_line1' => 'setBillingAddressLine1',
        'billing_address_line2' => 'setBillingAddressLine2',
        'billing_address_city' => 'setBillingAddressCity',
        'billing_address_state' => 'setBillingAddressState',
        'billing_address_zip' => 'setBillingAddressZip',
        'billing_address_country' => 'setBillingAddressCountry'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'type' => 'getType',
        'brand' => 'getBrand',
        'last_four_digits' => 'getLastFourDigits',
        'month' => 'getMonth',
        'year' => 'getYear',
        'field55' => 'getField55',
        'cardnet_status' => 'getCardnetStatus',
        'approval_number' => 'getApprovalNumber',
        'shipping_address_name' => 'getShippingAddressName',
        'shipping_address_line1' => 'getShippingAddressLine1',
        'shipping_address_line2' => 'getShippingAddressLine2',
        'shipping_address_city' => 'getShippingAddressCity',
        'shipping_address_state' => 'getShippingAddressState',
        'shipping_address_zip' => 'getShippingAddressZip',
        'shipping_address_country' => 'getShippingAddressCountry',
        'billing_address_name' => 'getBillingAddressName',
        'billing_address_line1' => 'getBillingAddressLine1',
        'billing_address_line2' => 'getBillingAddressLine2',
        'billing_address_city' => 'getBillingAddressCity',
        'billing_address_state' => 'getBillingAddressState',
        'billing_address_zip' => 'getBillingAddressZip',
        'billing_address_country' => 'getBillingAddressCountry'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const TYPE_CREDIT_CARD_TERMINAL = 'credit_card_terminal';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getTypeAllowableValues()
    {
        return [
            self::TYPE_CREDIT_CARD_TERMINAL,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('type', $data ?? [], null);
        $this->setIfExists('brand', $data ?? [], null);
        $this->setIfExists('last_four_digits', $data ?? [], null);
        $this->setIfExists('month', $data ?? [], null);
        $this->setIfExists('year', $data ?? [], null);
        $this->setIfExists('field55', $data ?? [], null);
        $this->setIfExists('cardnet_status', $data ?? [], null);
        $this->setIfExists('approval_number', $data ?? [], null);
        $this->setIfExists('shipping_address_name', $data ?? [], null);
        $this->setIfExists('shipping_address_line1', $data ?? [], null);
        $this->setIfExists('shipping_address_line2', $data ?? [], null);
        $this->setIfExists('shipping_address_city', $data ?? [], null);
        $this->setIfExists('shipping_address_state', $data ?? [], null);
        $this->setIfExists('shipping_address_zip', $data ?? [], null);
        $this->setIfExists('shipping_address_country', $data ?? [], null);
        $this->setIfExists('billing_address_name', $data ?? [], null);
        $this->setIfExists('billing_address_line1', $data ?? [], null);
        $this->setIfExists('billing_address_line2', $data ?? [], null);
        $this->setIfExists('billing_address_city', $data ?? [], null);
        $this->setIfExists('billing_address_state', $data ?? [], null);
        $this->setIfExists('billing_address_zip', $data ?? [], null);
        $this->setIfExists('billing_address_country', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['type'] === null) {
            $invalidProperties[] = "'type' can't be null";
        }
        if (!is_null($this->container['month']) && ($this->container['month'] > 12)) {
            $invalidProperties[] = "invalid value for 'month', must be smaller than or equal to 12.";
        }

        if (!is_null($this->container['month']) && ($this->container['month'] < 1)) {
            $invalidProperties[] = "invalid value for 'month', must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['year']) && ($this->container['year'] > 2100)) {
            $invalidProperties[] = "invalid value for 'year', must be smaller than or equal to 2100.";
        }

        if (!is_null($this->container['year']) && ($this->container['year'] < 0)) {
            $invalidProperties[] = "invalid value for 'year', must be bigger than or equal to 0.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets type
     *
     * @return string
     */
    public function getType()
    {
        return $this->container['type'];
    }

    /**
     * Sets type
     *
     * @param string $type Payment method type.
     *
     * @return self
     */
    public function setType($type)
    {
        if (is_null($type)) {
            throw new \InvalidArgumentException('non-nullable type cannot be null');
        }
        $this->container['type'] = $type;

        return $this;
    }

    /**
     * Gets brand
     *
     * @return string|null
     */
    public function getBrand()
    {
        return $this->container['brand'];
    }

    /**
     * Sets brand
     *
     * @param string|null $brand Card brand (e.g. \"visa\", \"mastercard\").
     *
     * @return self
     */
    public function setBrand($brand)
    {
        if (is_null($brand)) {
            throw new \InvalidArgumentException('non-nullable brand cannot be null');
        }
        $this->container['brand'] = $brand;

        return $this;
    }

    /**
     * Gets last_four_digits
     *
     * @return string|null
     */
    public function getLastFourDigits()
    {
        return $this->container['last_four_digits'];
    }

    /**
     * Sets last_four_digits
     *
     * @param string|null $last_four_digits Last four digits of the card used.
     *
     * @return self
     */
    public function setLastFourDigits($last_four_digits)
    {
        if (is_null($last_four_digits)) {
            throw new \InvalidArgumentException('non-nullable last_four_digits cannot be null');
        }
        $this->container['last_four_digits'] = $last_four_digits;

        return $this;
    }

    /**
     * Gets month
     *
     * @return int|null
     */
    public function getMonth()
    {
        return $this->container['month'];
    }

    /**
     * Sets month
     *
     * @param int|null $month Credit card expiration month.
     *
     * @return self
     */
    public function setMonth($month)
    {
        if (is_null($month)) {
            throw new \InvalidArgumentException('non-nullable month cannot be null');
        }

        if (($month > 12)) {
            throw new \InvalidArgumentException('invalid value for $month when calling ResponsePaymentDetailsCreditCardTerminal., must be smaller than or equal to 12.');
        }
        if (($month < 1)) {
            throw new \InvalidArgumentException('invalid value for $month when calling ResponsePaymentDetailsCreditCardTerminal., must be bigger than or equal to 1.');
        }

        $this->container['month'] = $month;

        return $this;
    }

    /**
     * Gets year
     *
     * @return int|null
     */
    public function getYear()
    {
        return $this->container['year'];
    }

    /**
     * Sets year
     *
     * @param int|null $year Credit card expiration year.  If this value is less than 100, it will be treated as two digits year in the current century. E.g. If current year is `2024`, `99` means `2099`.
     *
     * @return self
     */
    public function setYear($year)
    {
        if (is_null($year)) {
            throw new \InvalidArgumentException('non-nullable year cannot be null');
        }

        if (($year > 2100)) {
            throw new \InvalidArgumentException('invalid value for $year when calling ResponsePaymentDetailsCreditCardTerminal., must be smaller than or equal to 2100.');
        }
        if (($year < 0)) {
            throw new \InvalidArgumentException('invalid value for $year when calling ResponsePaymentDetailsCreditCardTerminal., must be bigger than or equal to 0.');
        }

        $this->container['year'] = $year;

        return $this;
    }

    /**
     * Gets field55
     *
     * @return string|null
     */
    public function getField55()
    {
        return $this->container['field55'];
    }

    /**
     * Sets field55
     *
     * @param string|null $field55 
     *
     * @return self
     */
    public function setField55($field55)
    {
        if (is_null($field55)) {
            throw new \InvalidArgumentException('non-nullable field55 cannot be null');
        }
        $this->container['field55'] = $field55;

        return $this;
    }

    /**
     * Gets cardnet_status
     *
     * @return string|null
     */
    public function getCardnetStatus()
    {
        return $this->container['cardnet_status'];
    }

    /**
     * Sets cardnet_status
     *
     * @param string|null $cardnet_status Status code returned by the Cardnet network.
     *
     * @return self
     */
    public function setCardnetStatus($cardnet_status)
    {
        if (is_null($cardnet_status)) {
            throw new \InvalidArgumentException('non-nullable cardnet_status cannot be null');
        }
        $this->container['cardnet_status'] = $cardnet_status;

        return $this;
    }

    /**
     * Gets approval_number
     *
     * @return string|null
     */
    public function getApprovalNumber()
    {
        return $this->container['approval_number'];
    }

    /**
     * Sets approval_number
     *
     * @param string|null $approval_number Approval number returned by the card network.
     *
     * @return self
     */
    public function setApprovalNumber($approval_number)
    {
        if (is_null($approval_number)) {
            throw new \InvalidArgumentException('non-nullable approval_number cannot be null');
        }
        $this->container['approval_number'] = $approval_number;

        return $this;
    }

    /**
     * Gets shipping_address_name
     *
     * @return string|null
     */
    public function getShippingAddressName()
    {
        return $this->container['shipping_address_name'];
    }

    /**
     * Sets shipping_address_name
     *
     * @param string|null $shipping_address_name Shipping address name. This is the recipient's name.
     *
     * @return self
     */
    public function setShippingAddressName($shipping_address_name)
    {
        if (is_null($shipping_address_name)) {
            throw new \InvalidArgumentException('non-nullable shipping_address_name cannot be null');
        }
        $this->container['shipping_address_name'] = $shipping_address_name;

        return $this;
    }

    /**
     * Gets shipping_address_line1
     *
     * @return string|null
     */
    public function getShippingAddressLine1()
    {
        return $this->container['shipping_address_line1'];
    }

    /**
     * Sets shipping_address_line1
     *
     * @param string|null $shipping_address_line1 Shipping address line 1.
     *
     * @return self
     */
    public function setShippingAddressLine1($shipping_address_line1)
    {
        if (is_null($shipping_address_line1)) {
            throw new \InvalidArgumentException('non-nullable shipping_address_line1 cannot be null');
        }
        $this->container['shipping_address_line1'] = $shipping_address_line1;

        return $this;
    }

    /**
     * Gets shipping_address_line2
     *
     * @return string|null
     */
    public function getShippingAddressLine2()
    {
        return $this->container['shipping_address_line2'];
    }

    /**
     * Sets shipping_address_line2
     *
     * @param string|null $shipping_address_line2 Shipping address line 2.
     *
     * @return self
     */
    public function setShippingAddressLine2($shipping_address_line2)
    {
        if (is_null($shipping_address_line2)) {
            throw new \InvalidArgumentException('non-nullable shipping_address_line2 cannot be null');
        }
        $this->container['shipping_address_line2'] = $shipping_address_line2;

        return $this;
    }

    /**
     * Gets shipping_address_city
     *
     * @return string|null
     */
    public function getShippingAddressCity()
    {
        return $this->container['shipping_address_city'];
    }

    /**
     * Sets shipping_address_city
     *
     * @param string|null $shipping_address_city Shipping address city.
     *
     * @return self
     */
    public function setShippingAddressCity($shipping_address_city)
    {
        if (is_null($shipping_address_city)) {
            throw new \InvalidArgumentException('non-nullable shipping_address_city cannot be null');
        }
        $this->container['shipping_address_city'] = $shipping_address_city;

        return $this;
    }

    /**
     * Gets shipping_address_state
     *
     * @return string|null
     */
    public function getShippingAddressState()
    {
        return $this->container['shipping_address_state'];
    }

    /**
     * Sets shipping_address_state
     *
     * @param string|null $shipping_address_state Shipping address state.
     *
     * @return self
     */
    public function setShippingAddressState($shipping_address_state)
    {
        if (is_null($shipping_address_state)) {
            throw new \InvalidArgumentException('non-nullable shipping_address_state cannot be null');
        }
        $this->container['shipping_address_state'] = $shipping_address_state;

        return $this;
    }

    /**
     * Gets shipping_address_zip
     *
     * @return string|null
     */
    public function getShippingAddressZip()
    {
        return $this->container['shipping_address_zip'];
    }

    /**
     * Sets shipping_address_zip
     *
     * @param string|null $shipping_address_zip Shipping address ZIP code.
     *
     * @return self
     */
    public function setShippingAddressZip($shipping_address_zip)
    {
        if (is_null($shipping_address_zip)) {
            throw new \InvalidArgumentException('non-nullable shipping_address_zip cannot be null');
        }
        $this->container['shipping_address_zip'] = $shipping_address_zip;

        return $this;
    }

    /**
     * Gets shipping_address_country
     *
     * @return string|null
     */
    public function getShippingAddressCountry()
    {
        return $this->container['shipping_address_country'];
    }

    /**
     * Sets shipping_address_country
     *
     * @param string|null $shipping_address_country Shipping address country.
     *
     * @return self
     */
    public function setShippingAddressCountry($shipping_address_country)
    {
        if (is_null($shipping_address_country)) {
            throw new \InvalidArgumentException('non-nullable shipping_address_country cannot be null');
        }
        $this->container['shipping_address_country'] = $shipping_address_country;

        return $this;
    }

    /**
     * Gets billing_address_name
     *
     * @return string|null
     */
    public function getBillingAddressName()
    {
        return $this->container['billing_address_name'];
    }

    /**
     * Sets billing_address_name
     *
     * @param string|null $billing_address_name Billing address name. This is the paying customer's name.
     *
     * @return self
     */
    public function setBillingAddressName($billing_address_name)
    {
        if (is_null($billing_address_name)) {
            throw new \InvalidArgumentException('non-nullable billing_address_name cannot be null');
        }
        $this->container['billing_address_name'] = $billing_address_name;

        return $this;
    }

    /**
     * Gets billing_address_line1
     *
     * @return string|null
     */
    public function getBillingAddressLine1()
    {
        return $this->container['billing_address_line1'];
    }

    /**
     * Sets billing_address_line1
     *
     * @param string|null $billing_address_line1 Billing address line 1.
     *
     * @return self
     */
    public function setBillingAddressLine1($billing_address_line1)
    {
        if (is_null($billing_address_line1)) {
            throw new \InvalidArgumentException('non-nullable billing_address_line1 cannot be null');
        }
        $this->container['billing_address_line1'] = $billing_address_line1;

        return $this;
    }

    /**
     * Gets billing_address_line2
     *
     * @return string|null
     */
    public function getBillingAddressLine2()
    {
        return $this->container['billing_address_line2'];
    }

    /**
     * Sets billing_address_line2
     *
     * @param string|null $billing_address_line2 Billing address line 2.
     *
     * @return self
     */
    public function setBillingAddressLine2($billing_address_line2)
    {
        if (is_null($billing_address_line2)) {
            throw new \InvalidArgumentException('non-nullable billing_address_line2 cannot be null');
        }
        $this->container['billing_address_line2'] = $billing_address_line2;

        return $this;
    }

    /**
     * Gets billing_address_city
     *
     * @return string|null
     */
    public function getBillingAddressCity()
    {
        return $this->container['billing_address_city'];
    }

    /**
     * Sets billing_address_city
     *
     * @param string|null $billing_address_city Billing address city.
     *
     * @return self
     */
    public function setBillingAddressCity($billing_address_city)
    {
        if (is_null($billing_address_city)) {
            throw new \InvalidArgumentException('non-nullable billing_address_city cannot be null');
        }
        $this->container['billing_address_city'] = $billing_address_city;

        return $this;
    }

    /**
     * Gets billing_address_state
     *
     * @return string|null
     */
    public function getBillingAddressState()
    {
        return $this->container['billing_address_state'];
    }

    /**
     * Sets billing_address_state
     *
     * @param string|null $billing_address_state Billing address state.
     *
     * @return self
     */
    public function setBillingAddressState($billing_address_state)
    {
        if (is_null($billing_address_state)) {
            throw new \InvalidArgumentException('non-nullable billing_address_state cannot be null');
        }
        $this->container['billing_address_state'] = $billing_address_state;

        return $this;
    }

    /**
     * Gets billing_address_zip
     *
     * @return string|null
     */
    public function getBillingAddressZip()
    {
        return $this->container['billing_address_zip'];
    }

    /**
     * Sets billing_address_zip
     *
     * @param string|null $billing_address_zip Billing address ZIP code.
     *
     * @return self
     */
    public function setBillingAddressZip($billing_address_zip)
    {
        if (is_null($billing_address_zip)) {
            throw new \InvalidArgumentException('non-nullable billing_address_zip cannot be null');
        }
        $this->container['billing_address_zip'] = $billing_address_zip;

        return $this;
    }

    /**
     * Gets billing_address_country
     *
     * @return string|null
     */
    public function getBillingAddressCountry()
    {
        return $this->container['billing_address_country'];
    }

    /**
     * Sets billing_address_country
     *
     * @param string|null $billing_address_country Billing address country.
     *
     * @return self
     */
    public function setBillingAddressCountry($billing_address_country)
    {
        if (is_null($billing_address_country)) {
            throw new \InvalidArgumentException('non-nullable billing_address_country cannot be null');
        }
        $this->container['billing_address_country'] = $billing_address_country;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


