<?php
/**
 * SessionMode
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Komoju
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * KOMOJU API
 *
 * Full featured access to the KOMOJU payments system.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.23.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Komoju\Model;
use \Komoju\ObjectSerializer;

/**
 * SessionMode Class Doc Comment
 *
 * @category Class
 * @description Specifies what to do with the payment details. Can create a payment, or a customer resource.
 * @package  Komoju
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class SessionMode
{
    /**
     * Possible values of this enum
     */
    public const PAYMENT = 'payment';

    public const CUSTOMER = 'customer';

    public const CUSTOMER_PAYMENT = 'customer_payment';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::PAYMENT,
            self::CUSTOMER,
            self::CUSTOMER_PAYMENT
        ];
    }
}


