<?php
/**
 * SharedDetails
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Komoju
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * KOMOJU API
 *
 * Full featured access to the KOMOJU payments system.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.9.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Komoju\Model;

use \ArrayAccess;
use \Komoju\ObjectSerializer;

/**
 * SharedDetails Class Doc Comment
 *
 * @category Class
 * @package  Komoju
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class SharedDetails implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'SharedDetails';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'payments' => '\Komoju\Model\SharedDetailsPayments',
        'refunds' => '\Komoju\Model\SharedDetailsRefunds',
        'platform_model' => '\Komoju\Model\SharedDetailsPlatformModel',
        'corrections' => '\Komoju\Model\SharedDetailsCorrections',
        'komoju_card_charges' => '\Komoju\Model\SharedDetailsCorrections',
        'disbursements' => '\Komoju\Model\SharedDetailsDisbursements',
        'misc' => '\Komoju\Model\SharedDetailsMisc'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'payments' => null,
        'refunds' => null,
        'platform_model' => null,
        'corrections' => null,
        'komoju_card_charges' => null,
        'disbursements' => null,
        'misc' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'payments' => false,
        'refunds' => false,
        'platform_model' => false,
        'corrections' => false,
        'komoju_card_charges' => false,
        'disbursements' => false,
        'misc' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'payments' => 'payments',
        'refunds' => 'refunds',
        'platform_model' => 'platform_model',
        'corrections' => 'corrections',
        'komoju_card_charges' => 'komoju_card_charges',
        'disbursements' => 'disbursements',
        'misc' => 'misc'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'payments' => 'setPayments',
        'refunds' => 'setRefunds',
        'platform_model' => 'setPlatformModel',
        'corrections' => 'setCorrections',
        'komoju_card_charges' => 'setKomojuCardCharges',
        'disbursements' => 'setDisbursements',
        'misc' => 'setMisc'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'payments' => 'getPayments',
        'refunds' => 'getRefunds',
        'platform_model' => 'getPlatformModel',
        'corrections' => 'getCorrections',
        'komoju_card_charges' => 'getKomojuCardCharges',
        'disbursements' => 'getDisbursements',
        'misc' => 'getMisc'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('payments', $data ?? [], null);
        $this->setIfExists('refunds', $data ?? [], null);
        $this->setIfExists('platform_model', $data ?? [], null);
        $this->setIfExists('corrections', $data ?? [], null);
        $this->setIfExists('komoju_card_charges', $data ?? [], null);
        $this->setIfExists('disbursements', $data ?? [], null);
        $this->setIfExists('misc', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['payments'] === null) {
            $invalidProperties[] = "'payments' can't be null";
        }
        if ($this->container['refunds'] === null) {
            $invalidProperties[] = "'refunds' can't be null";
        }
        if ($this->container['corrections'] === null) {
            $invalidProperties[] = "'corrections' can't be null";
        }
        if ($this->container['komoju_card_charges'] === null) {
            $invalidProperties[] = "'komoju_card_charges' can't be null";
        }
        if ($this->container['disbursements'] === null) {
            $invalidProperties[] = "'disbursements' can't be null";
        }
        if ($this->container['misc'] === null) {
            $invalidProperties[] = "'misc' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets payments
     *
     * @return \Komoju\Model\SharedDetailsPayments
     */
    public function getPayments()
    {
        return $this->container['payments'];
    }

    /**
     * Sets payments
     *
     * @param \Komoju\Model\SharedDetailsPayments $payments payments
     *
     * @return self
     */
    public function setPayments($payments)
    {
        if (is_null($payments)) {
            throw new \InvalidArgumentException('non-nullable payments cannot be null');
        }
        $this->container['payments'] = $payments;

        return $this;
    }

    /**
     * Gets refunds
     *
     * @return \Komoju\Model\SharedDetailsRefunds
     */
    public function getRefunds()
    {
        return $this->container['refunds'];
    }

    /**
     * Sets refunds
     *
     * @param \Komoju\Model\SharedDetailsRefunds $refunds refunds
     *
     * @return self
     */
    public function setRefunds($refunds)
    {
        if (is_null($refunds)) {
            throw new \InvalidArgumentException('non-nullable refunds cannot be null');
        }
        $this->container['refunds'] = $refunds;

        return $this;
    }

    /**
     * Gets platform_model
     *
     * @return \Komoju\Model\SharedDetailsPlatformModel|null
     */
    public function getPlatformModel()
    {
        return $this->container['platform_model'];
    }

    /**
     * Sets platform_model
     *
     * @param \Komoju\Model\SharedDetailsPlatformModel|null $platform_model platform_model
     *
     * @return self
     */
    public function setPlatformModel($platform_model)
    {
        if (is_null($platform_model)) {
            throw new \InvalidArgumentException('non-nullable platform_model cannot be null');
        }
        $this->container['platform_model'] = $platform_model;

        return $this;
    }

    /**
     * Gets corrections
     *
     * @return \Komoju\Model\SharedDetailsCorrections
     */
    public function getCorrections()
    {
        return $this->container['corrections'];
    }

    /**
     * Sets corrections
     *
     * @param \Komoju\Model\SharedDetailsCorrections $corrections corrections
     *
     * @return self
     */
    public function setCorrections($corrections)
    {
        if (is_null($corrections)) {
            throw new \InvalidArgumentException('non-nullable corrections cannot be null');
        }
        $this->container['corrections'] = $corrections;

        return $this;
    }

    /**
     * Gets komoju_card_charges
     *
     * @return \Komoju\Model\SharedDetailsCorrections
     */
    public function getKomojuCardCharges()
    {
        return $this->container['komoju_card_charges'];
    }

    /**
     * Sets komoju_card_charges
     *
     * @param \Komoju\Model\SharedDetailsCorrections $komoju_card_charges komoju_card_charges
     *
     * @return self
     */
    public function setKomojuCardCharges($komoju_card_charges)
    {
        if (is_null($komoju_card_charges)) {
            throw new \InvalidArgumentException('non-nullable komoju_card_charges cannot be null');
        }
        $this->container['komoju_card_charges'] = $komoju_card_charges;

        return $this;
    }

    /**
     * Gets disbursements
     *
     * @return \Komoju\Model\SharedDetailsDisbursements
     */
    public function getDisbursements()
    {
        return $this->container['disbursements'];
    }

    /**
     * Sets disbursements
     *
     * @param \Komoju\Model\SharedDetailsDisbursements $disbursements disbursements
     *
     * @return self
     */
    public function setDisbursements($disbursements)
    {
        if (is_null($disbursements)) {
            throw new \InvalidArgumentException('non-nullable disbursements cannot be null');
        }
        $this->container['disbursements'] = $disbursements;

        return $this;
    }

    /**
     * Gets misc
     *
     * @return \Komoju\Model\SharedDetailsMisc
     */
    public function getMisc()
    {
        return $this->container['misc'];
    }

    /**
     * Sets misc
     *
     * @param \Komoju\Model\SharedDetailsMisc $misc misc
     *
     * @return self
     */
    public function setMisc($misc)
    {
        if (is_null($misc)) {
            throw new \InvalidArgumentException('non-nullable misc cannot be null');
        }
        $this->container['misc'] = $misc;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


