<?php
/**
 * SharedDetailsMisc
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Komoju
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * KOMOJU API
 *
 * Full featured access to the KOMOJU payments system.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.23.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Komoju\Model;

use \ArrayAccess;
use \Komoju\ObjectSerializer;

/**
 * SharedDetailsMisc Class Doc Comment
 *
 * @category Class
 * @package  Komoju
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class SharedDetailsMisc implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'SharedDetails_misc';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'clearings_total_cents' => 'int',
        'komoju_card_discount_total_cents' => 'int',
        'chargeback_fixed_fee_total_cents' => 'int',
        'other_fee_adjustments_total_cents' => 'int',
        'total_cents' => 'int'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'clearings_total_cents' => 'int32',
        'komoju_card_discount_total_cents' => 'int32',
        'chargeback_fixed_fee_total_cents' => 'int32',
        'other_fee_adjustments_total_cents' => 'int32',
        'total_cents' => 'int32'
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'clearings_total_cents' => false,
        'komoju_card_discount_total_cents' => false,
        'chargeback_fixed_fee_total_cents' => false,
        'other_fee_adjustments_total_cents' => false,
        'total_cents' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'clearings_total_cents' => 'clearings_total_cents',
        'komoju_card_discount_total_cents' => 'komoju_card_discount_total_cents',
        'chargeback_fixed_fee_total_cents' => 'chargeback_fixed_fee_total_cents',
        'other_fee_adjustments_total_cents' => 'other_fee_adjustments_total_cents',
        'total_cents' => 'total_cents'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'clearings_total_cents' => 'setClearingsTotalCents',
        'komoju_card_discount_total_cents' => 'setKomojuCardDiscountTotalCents',
        'chargeback_fixed_fee_total_cents' => 'setChargebackFixedFeeTotalCents',
        'other_fee_adjustments_total_cents' => 'setOtherFeeAdjustmentsTotalCents',
        'total_cents' => 'setTotalCents'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'clearings_total_cents' => 'getClearingsTotalCents',
        'komoju_card_discount_total_cents' => 'getKomojuCardDiscountTotalCents',
        'chargeback_fixed_fee_total_cents' => 'getChargebackFixedFeeTotalCents',
        'other_fee_adjustments_total_cents' => 'getOtherFeeAdjustmentsTotalCents',
        'total_cents' => 'getTotalCents'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('clearings_total_cents', $data ?? [], null);
        $this->setIfExists('komoju_card_discount_total_cents', $data ?? [], null);
        $this->setIfExists('chargeback_fixed_fee_total_cents', $data ?? [], null);
        $this->setIfExists('other_fee_adjustments_total_cents', $data ?? [], null);
        $this->setIfExists('total_cents', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['clearings_total_cents'] === null) {
            $invalidProperties[] = "'clearings_total_cents' can't be null";
        }
        if ($this->container['komoju_card_discount_total_cents'] === null) {
            $invalidProperties[] = "'komoju_card_discount_total_cents' can't be null";
        }
        if ($this->container['chargeback_fixed_fee_total_cents'] === null) {
            $invalidProperties[] = "'chargeback_fixed_fee_total_cents' can't be null";
        }
        if ($this->container['other_fee_adjustments_total_cents'] === null) {
            $invalidProperties[] = "'other_fee_adjustments_total_cents' can't be null";
        }
        if ($this->container['total_cents'] === null) {
            $invalidProperties[] = "'total_cents' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets clearings_total_cents
     *
     * @return int
     */
    public function getClearingsTotalCents()
    {
        return $this->container['clearings_total_cents'];
    }

    /**
     * Sets clearings_total_cents
     *
     * @param int $clearings_total_cents Amount in the lowest denomination of the currency (e.g. cents for USD).
     *
     * @return self
     */
    public function setClearingsTotalCents($clearings_total_cents)
    {
        if (is_null($clearings_total_cents)) {
            throw new \InvalidArgumentException('non-nullable clearings_total_cents cannot be null');
        }
        $this->container['clearings_total_cents'] = $clearings_total_cents;

        return $this;
    }

    /**
     * Gets komoju_card_discount_total_cents
     *
     * @return int
     */
    public function getKomojuCardDiscountTotalCents()
    {
        return $this->container['komoju_card_discount_total_cents'];
    }

    /**
     * Sets komoju_card_discount_total_cents
     *
     * @param int $komoju_card_discount_total_cents Amount in the lowest denomination of the currency (e.g. cents for USD).
     *
     * @return self
     */
    public function setKomojuCardDiscountTotalCents($komoju_card_discount_total_cents)
    {
        if (is_null($komoju_card_discount_total_cents)) {
            throw new \InvalidArgumentException('non-nullable komoju_card_discount_total_cents cannot be null');
        }
        $this->container['komoju_card_discount_total_cents'] = $komoju_card_discount_total_cents;

        return $this;
    }

    /**
     * Gets chargeback_fixed_fee_total_cents
     *
     * @return int
     */
    public function getChargebackFixedFeeTotalCents()
    {
        return $this->container['chargeback_fixed_fee_total_cents'];
    }

    /**
     * Sets chargeback_fixed_fee_total_cents
     *
     * @param int $chargeback_fixed_fee_total_cents Amount in the lowest denomination of the currency (e.g. cents for USD).
     *
     * @return self
     */
    public function setChargebackFixedFeeTotalCents($chargeback_fixed_fee_total_cents)
    {
        if (is_null($chargeback_fixed_fee_total_cents)) {
            throw new \InvalidArgumentException('non-nullable chargeback_fixed_fee_total_cents cannot be null');
        }
        $this->container['chargeback_fixed_fee_total_cents'] = $chargeback_fixed_fee_total_cents;

        return $this;
    }

    /**
     * Gets other_fee_adjustments_total_cents
     *
     * @return int
     */
    public function getOtherFeeAdjustmentsTotalCents()
    {
        return $this->container['other_fee_adjustments_total_cents'];
    }

    /**
     * Sets other_fee_adjustments_total_cents
     *
     * @param int $other_fee_adjustments_total_cents Amount in the lowest denomination of the currency (e.g. cents for USD).
     *
     * @return self
     */
    public function setOtherFeeAdjustmentsTotalCents($other_fee_adjustments_total_cents)
    {
        if (is_null($other_fee_adjustments_total_cents)) {
            throw new \InvalidArgumentException('non-nullable other_fee_adjustments_total_cents cannot be null');
        }
        $this->container['other_fee_adjustments_total_cents'] = $other_fee_adjustments_total_cents;

        return $this;
    }

    /**
     * Gets total_cents
     *
     * @return int
     */
    public function getTotalCents()
    {
        return $this->container['total_cents'];
    }

    /**
     * Sets total_cents
     *
     * @param int $total_cents Amount in the lowest denomination of the currency (e.g. cents for USD).
     *
     * @return self
     */
    public function setTotalCents($total_cents)
    {
        if (is_null($total_cents)) {
            throw new \InvalidArgumentException('non-nullable total_cents cannot be null');
        }
        $this->container['total_cents'] = $total_cents;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


