<?php
/**
 * CreatePaymentRequestWithPaymentDetailsTaxTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Komoju
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * KOMOJU API
 *
 * Full featured access to the KOMOJU payments system.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.23.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Komoju\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * CreatePaymentRequestWithPaymentDetailsTaxTest Class Doc Comment
 *
 * @category    Class
 * @description The tax amount. Defaults to the highest consumption tax rate in Japan if omitted or set to &#x60;auto&#x60;.  It&#39;s recommended to set to &#x60;0&#x60; unless you want the tax amount to be tracked on KOMOJU.
 * @package     Komoju
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class CreatePaymentRequestWithPaymentDetailsTaxTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "CreatePaymentRequestWithPaymentDetailsTax"
     */
    public function testCreatePaymentRequestWithPaymentDetailsTax()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
