<?php
/**
 * DefendChargebackDocumentTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Komoju
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * KOMOJU API
 *
 * Full featured access to the KOMOJU payments system.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.23.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Komoju\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * DefendChargebackDocumentTest Class Doc Comment
 *
 * @category    Class
 * @description DefendChargebackDocument
 * @package     Komoju
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class DefendChargebackDocumentTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "DefendChargebackDocument"
     */
    public function testDefendChargebackDocument()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "document_base64"
     */
    public function testPropertyDocumentBase64()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "filename"
     */
    public function testPropertyFilename()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "content_type"
     */
    public function testPropertyContentType()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
