<?php
/**
 * LiveApplicationRequestTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Komoju
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * KOMOJU API
 *
 * Full featured access to the KOMOJU payments system.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.23.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Komoju\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * LiveApplicationRequestTest Class Doc Comment
 *
 * @category    Class
 * @description LiveApplicationRequest
 * @package     Komoju
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class LiveApplicationRequestTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "LiveApplicationRequest"
     */
    public function testLiveApplicationRequest()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "locale"
     */
    public function testPropertyLocale()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "service_agreement_agreed_to_tos"
     */
    public function testPropertyServiceAgreementAgreedToTos()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "company_information_company_name"
     */
    public function testPropertyCompanyInformationCompanyName()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "company_information_company_phone"
     */
    public function testPropertyCompanyInformationCompanyPhone()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "company_information_company_country"
     */
    public function testPropertyCompanyInformationCompanyCountry()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "company_information_corporation_type"
     */
    public function testPropertyCompanyInformationCorporationType()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "company_information_company_postal_code"
     */
    public function testPropertyCompanyInformationCompanyPostalCode()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "company_information_company_prefecture_state"
     */
    public function testPropertyCompanyInformationCompanyPrefectureState()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "company_information_company_prefecture_state_kana"
     */
    public function testPropertyCompanyInformationCompanyPrefectureStateKana()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "company_information_company_city"
     */
    public function testPropertyCompanyInformationCompanyCity()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "company_information_company_city_kana"
     */
    public function testPropertyCompanyInformationCompanyCityKana()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "company_information_company_address"
     */
    public function testPropertyCompanyInformationCompanyAddress()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "company_information_industry_description"
     */
    public function testPropertyCompanyInformationIndustryDescription()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "company_information_business_description"
     */
    public function testPropertyCompanyInformationBusinessDescription()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "company_information_employee_number"
     */
    public function testPropertyCompanyInformationEmployeeNumber()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "company_information_establishment_date"
     */
    public function testPropertyCompanyInformationEstablishmentDate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "company_information_office_name"
     */
    public function testPropertyCompanyInformationOfficeName()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "company_information_contact_email"
     */
    public function testPropertyCompanyInformationContactEmail()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "company_information_contact_phone"
     */
    public function testPropertyCompanyInformationContactPhone()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "company_information_incorporation_certificates"
     */
    public function testPropertyCompanyInformationIncorporationCertificates()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "company_information_registration_number"
     */
    public function testPropertyCompanyInformationRegistrationNumber()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "company_information_share_capital_amount"
     */
    public function testPropertyCompanyInformationShareCapitalAmount()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "company_information_share_capital_currency"
     */
    public function testPropertyCompanyInformationShareCapitalCurrency()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "company_information_sole_proprietor_proofs"
     */
    public function testPropertyCompanyInformationSoleProprietorProofs()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "company_information_company_name_kana"
     */
    public function testPropertyCompanyInformationCompanyNameKana()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "company_information_company_name_alphabet"
     */
    public function testPropertyCompanyInformationCompanyNameAlphabet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "company_information_company_url"
     */
    public function testPropertyCompanyInformationCompanyUrl()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "company_information_company_address_kana"
     */
    public function testPropertyCompanyInformationCompanyAddressKana()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "company_information_company_address_building_name"
     */
    public function testPropertyCompanyInformationCompanyAddressBuildingName()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "company_information_company_address_building_name_kana"
     */
    public function testPropertyCompanyInformationCompanyAddressBuildingNameKana()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "representative_director_information_first_name"
     */
    public function testPropertyRepresentativeDirectorInformationFirstName()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "representative_director_information_first_name_kana"
     */
    public function testPropertyRepresentativeDirectorInformationFirstNameKana()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "representative_director_information_last_name"
     */
    public function testPropertyRepresentativeDirectorInformationLastName()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "representative_director_information_last_name_kana"
     */
    public function testPropertyRepresentativeDirectorInformationLastNameKana()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "representative_director_information_date_of_birth"
     */
    public function testPropertyRepresentativeDirectorInformationDateOfBirth()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "representative_director_information_gender"
     */
    public function testPropertyRepresentativeDirectorInformationGender()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "representative_director_information_country"
     */
    public function testPropertyRepresentativeDirectorInformationCountry()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "representative_director_information_postal_code"
     */
    public function testPropertyRepresentativeDirectorInformationPostalCode()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "representative_director_information_prefecture_state"
     */
    public function testPropertyRepresentativeDirectorInformationPrefectureState()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "representative_director_information_prefecture_state_kana"
     */
    public function testPropertyRepresentativeDirectorInformationPrefectureStateKana()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "representative_director_information_city"
     */
    public function testPropertyRepresentativeDirectorInformationCity()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "representative_director_information_city_kana"
     */
    public function testPropertyRepresentativeDirectorInformationCityKana()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "representative_director_information_address"
     */
    public function testPropertyRepresentativeDirectorInformationAddress()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "representative_director_information_address_kana"
     */
    public function testPropertyRepresentativeDirectorInformationAddressKana()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "representative_director_information_address_building_name"
     */
    public function testPropertyRepresentativeDirectorInformationAddressBuildingName()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "representative_director_information_address_building_name_kana"
     */
    public function testPropertyRepresentativeDirectorInformationAddressBuildingNameKana()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "representative_director_information_phone"
     */
    public function testPropertyRepresentativeDirectorInformationPhone()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "applicant_information_first_name"
     */
    public function testPropertyApplicantInformationFirstName()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "applicant_information_first_name_kana"
     */
    public function testPropertyApplicantInformationFirstNameKana()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "applicant_information_last_name"
     */
    public function testPropertyApplicantInformationLastName()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "applicant_information_last_name_kana"
     */
    public function testPropertyApplicantInformationLastNameKana()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "applicant_information_country"
     */
    public function testPropertyApplicantInformationCountry()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "applicant_information_gender"
     */
    public function testPropertyApplicantInformationGender()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "applicant_information_date_of_birth"
     */
    public function testPropertyApplicantInformationDateOfBirth()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "applicant_information_identity_document_type"
     */
    public function testPropertyApplicantInformationIdentityDocumentType()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "applicant_information_identity_front"
     */
    public function testPropertyApplicantInformationIdentityFront()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "applicant_information_identity_back"
     */
    public function testPropertyApplicantInformationIdentityBack()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "site_information_site_name"
     */
    public function testPropertySiteInformationSiteName()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "site_information_site_name_kana"
     */
    public function testPropertySiteInformationSiteNameKana()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "site_information_site_name_alphabet"
     */
    public function testPropertySiteInformationSiteNameAlphabet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "site_information_site_url"
     */
    public function testPropertySiteInformationSiteUrl()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "site_information_establishment_date"
     */
    public function testPropertySiteInformationEstablishmentDate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "site_information_store_country"
     */
    public function testPropertySiteInformationStoreCountry()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "site_information_store_postal_code"
     */
    public function testPropertySiteInformationStorePostalCode()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "site_information_store_prefecture_state"
     */
    public function testPropertySiteInformationStorePrefectureState()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "site_information_store_prefecture_state_kana"
     */
    public function testPropertySiteInformationStorePrefectureStateKana()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "site_information_store_city"
     */
    public function testPropertySiteInformationStoreCity()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "site_information_store_city_kana"
     */
    public function testPropertySiteInformationStoreCityKana()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "site_information_store_address"
     */
    public function testPropertySiteInformationStoreAddress()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "site_information_store_address_kana"
     */
    public function testPropertySiteInformationStoreAddressKana()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "site_information_store_building_name"
     */
    public function testPropertySiteInformationStoreBuildingName()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "site_information_store_building_name_kana"
     */
    public function testPropertySiteInformationStoreBuildingNameKana()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "site_information_site_product_description"
     */
    public function testPropertySiteInformationSiteProductDescription()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "site_information_site_annual_sales"
     */
    public function testPropertySiteInformationSiteAnnualSales()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "site_information_site_annual_sales_currency"
     */
    public function testPropertySiteInformationSiteAnnualSalesCurrency()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "site_information_site_average_transactional_value"
     */
    public function testPropertySiteInformationSiteAverageTransactionalValue()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "site_information_site_average_transactional_currency"
     */
    public function testPropertySiteInformationSiteAverageTransactionalCurrency()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "site_information_site_minimum_product_pricing_cents"
     */
    public function testPropertySiteInformationSiteMinimumProductPricingCents()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "site_information_site_minimum_product_pricing_currency"
     */
    public function testPropertySiteInformationSiteMinimumProductPricingCurrency()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "site_information_site_maximum_product_pricing_cents"
     */
    public function testPropertySiteInformationSiteMaximumProductPricingCents()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "site_information_site_maximum_product_pricing_currency"
     */
    public function testPropertySiteInformationSiteMaximumProductPricingCurrency()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "site_information_sctl_url"
     */
    public function testPropertySiteInformationSctlUrl()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "site_information_sales_permit_required"
     */
    public function testPropertySiteInformationSalesPermitRequired()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "site_information_aup_accepted"
     */
    public function testPropertySiteInformationAupAccepted()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "site_information_industry_type"
     */
    public function testPropertySiteInformationIndustryType()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "site_information_sales_permits"
     */
    public function testPropertySiteInformationSalesPermits()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "bank_account_information_zengin_bank_name"
     */
    public function testPropertyBankAccountInformationZenginBankName()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "bank_account_information_zengin_bank_code"
     */
    public function testPropertyBankAccountInformationZenginBankCode()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "bank_account_information_zengin_branch_name"
     */
    public function testPropertyBankAccountInformationZenginBranchName()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "bank_account_information_zengin_branch_code"
     */
    public function testPropertyBankAccountInformationZenginBranchCode()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "bank_account_information_zengin_account_type"
     */
    public function testPropertyBankAccountInformationZenginAccountType()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "bank_account_information_zengin_account_number"
     */
    public function testPropertyBankAccountInformationZenginAccountNumber()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "bank_account_information_zengin_account_holder_kana"
     */
    public function testPropertyBankAccountInformationZenginAccountHolderKana()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "bank_account_information_transfer_type"
     */
    public function testPropertyBankAccountInformationTransferType()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "bank_account_information_currency"
     */
    public function testPropertyBankAccountInformationCurrency()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "bank_account_information_default_frequency"
     */
    public function testPropertyBankAccountInformationDefaultFrequency()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
